import type { AttributionsParTexte } from "./socle";

/**
 * Le cabinet du ministre — arrêté n° 25564.
 *
 * Transcrit du Journal officiel, article par article. Les intitulés sont
 * ceux du texte : c'est par eux que l'entité est retrouvée.
 */
export const CABINET: AttributionsParTexte = {
  "25564": {
    "direction des études et de la planification": [3,
    ],
    "direction des examens et concours techniques et professionnels": [4,
      "organiser les examens et les concours",
      "délivrer les diplômes et certificats sanctionnant la fin des formations dans les cycles de l'enseignement technique et professionnel",
    ],
    "service des baccalauréats technique et professionnel": [6,
      "préparer, au plan administratif et matériel,",
      "toutes les opérations relatives à l'organisation des baccalauréats",
      "organiser le travail relatif à la réception et au traitement des dossiers de candidature aux baccalauréats",
      "valider les inscriptions des candidats aux baccalauréats",
      "préparer les centres de déroulement des baccalauréats",
      "s'informer auprès de l'inspection générale sur l'état d'avancement des programmes des classes de fin de cycle",
      "mettre au point la fiche de tirage des sujets",
      "assurer la publication des résultats après délibération",
      "mettre en œuvre les différentes opérations liées à l'organisation et au déroulement des baccalauréats",
      "initier les différentes notes de service relatives à l'organisation des baccalauréats",
    ],
    "bureau baccalauréat des séries industrielles et commerciales": [8,
      "préparer les fiches d'inscription des candidatures au baccalauréat des séries industrielles et commerciales",
      "réceptionner les dossiers, traiter et inscrire les candidats aux baccalauréats des séries industrielles et commerciales",
      "préparer les opérations liées au déroulement du baccalauréat industriel et commercial",
    ],
    "bureau baccalauréat des séries agricoles et professionnelles": [9,
      "préparer les fiches d'inscription des candidatures au baccalauréat des séries agricoles et professionnelles",
      "réceptionner les dossiers, traiter et inscrire des candidatures au baccalauréat des séries agricoles et professionnelles",
      "préparer les opérations liées au déroulement du baccalauréat des séries agricoles et professionnelles",
    ],
    "service des brevets technique et professionnel": [10,
      "préparer, au plan administratif et matériel, toutes les opérations relatives à l'organisation des brevets, techniques et professionnels et du certificat d'aptitudes professionnelles",
      "organiser le travail relatif à la réception et au traitement des dossiers des candidatures aux brevets techniques et professionnels et au certificat d'aptitude professionnelle",
      "valider les inscriptions des candidatures aux brevets techniques et professionnels et au certificat d'aptitude professionnelle",
      "préparer les centres de déroulement des brevets techniques et professionnels et du certificat d'aptitude professionnelle",
      "mettre au point la fiche de tirage des sujets",
      "s'informer auprès de l'inspection générale sur l'état d'avancement des programmes des classes de fin de cycle",
      "mettre en œuvre les différentes opérations liées à l'organisation et au déroulement des brevets techniques et professionnels et du certificat d'aptitude professionnelle",
      "assurer la publication des résultats après délibération",
      "initier les différentes notes relatives aux opérations liées à l'organisation des brevets techniques et professionnels et du certificat d'aptitude professionnelle",
    ],
    "bureau des brevets des études techniques": [12,
      "préparer les fiches d'inscription des candidatures au brevet d'études techniques",
      "réceptionner les dossiers, traiter et inscrire les candidatures au brevet d'études techniques",
      "préparer les opérations liées au déroulement du brevet d'études techniques",
    ],
    "bureau des brevets des études professionnels et des brevets des études forestiers": [13,
      "préparer les fiches d'inscription des candidats aux brevets d'études professionnelles et au brevet de technicien forestier",
      "réceptionner les dossiers, traiter et inscrire des candidats aux brevets d'études professionnelles et au brevet de technicien forestier",
      "préparer les opérations liées au déroulement des brevets d'études professionnelles et au brevet de technicien forestier",
    ],
    "bureau des certificats des études d'aptitude professionnel": [14,
      "préparer les fiches d'inscription des candidatures au certificat d'aptitudes professionnelles",
      "réceptionner les dossiers, traiter et inscrire les candidatures au certificat d'aptitudes professionnelles",
      "préparer les opérations liées au déroulement du certificat d'aptitude professionnelle",
    ],
    "service des examens professionnels et des concours": [15,
      "préparer au plan administratif et matériel toutes les opérations relatives à l'organisation des examens et concours professionnels",
      "organiser la réception et le traitement des dossiers des candidatures aux examens et concours professionnels",
      "valider les inscriptions des candidatures aux examens professionnels et concours",
      "préparer les centres de déroulement des examens et concours professionnels, mettre au point la fiche de tirage des sujets",
      "mettre en œuvre les différentes opérations liées à l'organisation et au déroulement des examens et concours professionnels",
      "s'informer auprès de l'inspection générale sur l'état d'avancement des programmes des classes de fin de cycle",
      "assurer la publication des résultats après délibération",
      "initier les différentes notes relatives à l'organisation des examens et concours professionnels",
    ],
    "bureau des examens professionnels": [17,
      "préparer les fiches d'inscription des candidats aux différents examens professionnels",
      "réceptionner les dossiers, traiter et inscrire les candidats aux différents examens professionnels",
      "préparer les opérations liées au déroulement des différents examens professionnels",
    ],
    "bureau des concours": [18,
      "préparer les fiches d'inscription des candidatures aux concours",
      "réceptionner les dossiers, traiter et inscrire les candidatures aux concours",
      "préparer les opérations liées au déroulement des concours",
    ],
    "service des diplômes": [19,
      "recevoir les demandes d'établissement des diplômes, des attestations de réussite aux examens et concours ainsi que des relevés de notes",
      "contrôler et vérifier l'authenticité des diplômes",
      "assurer la délivrance des diplômes et des attestations de réussite aux examens et concours ainsi que des relevés de notes",
      "connaitre du contentieux relatif à la délivrance et/ou à l'établissement des diplômes et attestations",
    ],
    "bureau contrôle, vérification et délivrance": [21,
      "recevoir les demandes d'établissement des diplômes et des attestations de réussite aux examens et concours ainsi que des relevés de notes",
      "contrôler et vérifier l'authenticité des diplômes",
      "certifier les copies des diplômes et autres titres d'admission",
      "assurer le relais entre la direction des examens et concours techniques et professionnels et les universités publiques",
      "délivrer les diplômes et autres titres d'admission",
    ],
    "service des diplômes > bureau du contentieux": [22,
      "réceptionner les requêtes et autres contentieux relatifs à l'établissement et/ou à la délivrance des diplômes et des attestations de réussite aux examens et concours ainsi que des relevés de notes",
      "connaitre du contentieux relatif à l'établissement et/ou à la délivrance des diplômes et autres attestations",
    ],
    "service de l'informatique": [23,
      "réaliser la saisie et la reprographie des dossiers relatifs aux examens et concours techniques et professionnels ainsi que d'autres documents de la direction des examens et concours techniques et professionnels",
      "contrôler l'authenticité des documents ou dossiers à saisir",
      "éditer les diplômes et autres documents",
      "assurer la maintenance informatique",
    ],
    "bureau de l'informatique et de la maintenance": [25,
      "assurer la veille technologique",
      "organiser le système informatique",
      "assurer le lien informatique entre les différents services de la direction des examens et concours techniques et professionnels",
      "assurer la maintenance informatique",
    ],
    "bureau de la saisie et de la reprographie": [26,
      "saisir les dossiers des examens et concours",
      "contrôler l'authenticité des dossiers ou documents à saisir",
      "saisir les listes provisoires des candidats aux différents examens et concours",
      "éditer les diplômes et autres documents",
      "reprographier tous les documents",
      "confectionner les badges des agents",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "service des finances et du matériel > service des finances et du matériel": [27,
      "élaborer le projet du budget des examens et concours",
      "gérer les finances relatives à l'organisation des examens et concours",
      "élaborer les fiches financières relatives à l'organisation des examens et concours",
      "recouvrer les frais d'inscription des candidats aux examens et concours",
      "recouvrer les frais de déclaration et légalisation des titres d'admission aux examens et concours",
      "gérer le matériel",
    ],
    "service des finances et du matériel > bureau des finances": [29,
      "préparer les données relatives à l'élaboration du budget des examens et concours",
      "recouvrer les frais d'inscription aux différents examens et concours",
      "recouvrer les menues recettes",
      "préparer les documents relatifs à la mise en œuvre des dépenses relatives à l'organisation des examens et concours",
    ],
    "service des finances et du matériel > bureau du matériel": [30,
      "gérer le stock du matériel",
      "préparer les états de besoin en matériel",
      "mettre au point le matériel et la matière d'œuvre relatifs à l'organisation des examens et concours",
    ],
    "bureau de contrôle et vérification": [31,
      "contrôler et vérifier les documents comptables",
      "contrôler et vérifier le stock du matériel",
      "contrôler et vérifier la gestion du matériel",
      "tenir à jour les rapports y relatifs",
    ],
    "direction des systèmes d'information et de la communication": [32,
      "proposer, étudier, développer, déployer et mettre en œuvre les systèmes d'information et de communication du ministère",
      "assurer la veille technologique des systèmes d'information et de communication",
      "contribuer à la mise en place de la politique d'achat d'équipements informatiques et de logiciels des structures relevant du ministère",
      "contribuer à la mise en place de la politique de formation et de renforcement des capacités du personnel du ministère en informatique",
      "constituer les fonds documentaires et assurer la diffusion de l'information du ministère",
      "assurer le traitement informatique des examens d'État et des concours",
      "assurer le traitement informatique des flux scolaires",
      "produire les statistiques des examens, des concours et des flux scolaires",
    ],
    "service des applications": [34,
      "participer à la réalisation des cahiers des charges des applications du ministère à développer",
      "participer à la réalisation, au déploiement et à la mise en œuvre des systèmes d'information et de communication du ministère",
      "assurer la maintenance des applications du ministère",
      "assurer la formation des utilisateurs à l'usage des applications du ministère",
      "élaborer les stratégies de sécurité pour l'ensemble des systèmes d'information du ministère",
      "assurer la veille technologie des systèmes d'information et de communication du ministère",
      "assurer le traitement informatique des examens et concours techniques et professionnels",
      "assurer le déploiement des technologies de l'information et de la communication au sein des établissements de l'enseignement technique et professionnel",
      "assurer le traitement informatique des flux scolaires du ministère",
    ],
    "bureau de la réalisation de l'intégration et de l'assistance aux utilisateurs": [36,
      "contribuer à la réalisation et au déploiement des systèmes d'information, des logiciels, des applications éducatives et des sites internet du ministère",
      "assurer les mises à jour des systèmes d'information et de communication",
      "réaliser les tests et coordonner les processus d'intégration des logiciels",
      "installer et configurer les applications du ministère",
      "contribuer à l'élaboration des manuels d'utilisations des outils numériques du ministère",
      "contribuer à la formation des utilisateurs à l'usage des applications du ministère",
      "assister les utilisateurs des applications du ministère",
    ],
    "bureau de l'exploitation du système d'information des examens et concours techniques et professionnels": [37,
      "contribuer à la planification des opérations du traitement informatique des examens et concours techniques et professionnels",
      "administrer le serveur des bases de données et le réseau informatique du système d'information de traitement des examens et concours techniques et professionnels",
      "assurer le stockage des données des examens et concours techniques et professionnels",
      "gérer les ressources techniques dédiées au système d'information, notamment les pièces de rechange des ordinateurs, les supports de sauvegarde et les supports logiciels",
      "contribuer à la rédaction des procédures du traitement informatique des examens et concours techniques et professionnels",
      "garantir l'opérationnalité de la base de données des examens et concours techniques et professionnels",
      "exécuter le système de sécurité mis en place en matière de traitement des examens et concours techniques et professionnels",
      "suivre l'évolution du système de sécurité",
      "suivre le respect de la pratique sécuritaire pendant le traitement informatique des examens et concours techniques et professionnels",
      "veiller à la protection des données avant et après le traitement informatique des examens et concours techniques et professionnels",
      "contribuer à la production des statistiques des inscriptions et des résultats des examens et concours techniques et professionnels",
    ],
    "bureau de l'exploitation du système d'information de gestion de l'éducation": [38,
      "contribuer à la planification des opérations du traitement informatique des flux scolaires",
      "administrer le serveur des bases de données et le réseau informatique du système d'information des flux scolaires",
      "assurer le stockage des données des flux scolaires",
      "gérer les ressources techniques dédiées au système d'information, notamment les pièces de rechange des ordinateurs, les supports de sauvegarde et les supports logiciels",
      "contribuer à la rédaction des procédures du traitement informatique de la gestion scolaire",
      "garantir l'opérationnalité de la base de données des flux scolaires",
      "exécuter le système de sécurité mis en place en matière de traitement des flux scolaires",
      "suivre l'évolution du système de sécurité",
      "suivre le respect de la pratique sécuritaire pendant le traitement informatique des flux scolaires",
      "contribuer à la production des statistiques des flux scolaires",
      "promouvoir avec le concours des directions générales l'utilisation des technologies de l'information et de la communication dans les établissements techniques et professionnels",
      "contribuer à la réduction de la fracture numérique au sein du ministère",
    ],
    "service des infrastructures et de soutien aux utilisateurs": [39,
      "promouvoir l'informatisation des entités administratives du ministère",
      "appuyer les activités des centres de documentation et d'information des établissements dans le domaine des technologies de l'information et de la communication",
      "assurer la maintenance des équipements informatiques, de télécommunication et des réseaux du ministère",
      "contribuer à la mise en place de la politique d'achat d'équipements informatiques et des logiciels des structures du ministère",
      "participer au traitement informatique des examens d'État et concours techniques et professionnels, des flux scolaires et des données des personnels du ministère",
      "mettre en place un système de veille technologique",
    ],
    "bureau de la maintenance des infrastructures": [41,
      "contribuer à la maintenance des équipements informatiques, de télécommunication et des réseaux du ministère",
      "spécifier les caractéristiques techniques des équipements informatiques, les garanties nécessaires ainsi que leurs conditions d'utilisation",
      "contribuer à la préparation du dispositif technique du traitement informatique des examens d'Etat et concours techniques et professionnels",
      "participer à la mise en œuvre des projets d'informatisation du ministère et en assurer le suivi",
      "participer à l'analyse, à la migration et à la vulgarisation des infrastructures du ministère",
    ],
    "bureau de la formation et du soutien aux utilisateurs": [42,
      "identifier les besoins en formation du personnel du ministère en informatique",
      "élaborer et exécuter les programmes de formation du personnel du ministère en informatique",
      "assister l'ensemble des services du ministère dans l'exploitation de leurs systèmes d'information et communication respectifs",
      "veiller à l'usage des technologies de l'information et de la communication dans les centres de documentation et d'information des établissements",
      "faire la promotion des technologies de la communication en milieu scolaire et dans les administrations du ministère",
      "promouvoir et vulgariser les applications informatiques dans le processus de formation et des apprentissages",
    ],
    "service de la production, de la documentation et de la diffusion de l'information": [43,
      "collecter, organiser, traiter et gérer le fonds documentaire du ministère",
      "mettre à la disposition des utilisateurs les outils et les documents devant favoriser la recherche de l'information",
      "participer à la pérennisation du patrimoine documentaire du ministère à travers l'archivage électronique",
      "participer à la promotion et à la coordination des activités des centres de documentation, d'information et d'orientation",
      "participer au traitement informatique des examens d'État et des concours",
      "faire des publications et des reprographies en matière d'enseignement technique et professionnel",
      "participer au choix de la solution de gestion électronique des documents et au choix du système d'archivage électronique",
    ],
    "bureau des acquisitions et de la production des outils de recherche": [45,
      "identifier les besoins en information des utilisateurs",
      "organiser la collecte des données pertinentes en vue de satisfaire la demande",
      "assurer le traitement de l'information à travers les opérations de tri, sélection, classement, indexation, codification, catalogage et de classification",
      "élaborer les outils de recherche notamment les statistiques, les bottins, les bulletins, les abstracts ou résumés, les coupures de presse, les listes des acquisitions",
      "contribuer à l'appui technique des centres de documentation et d'information des établissements en matière de gestion documentaire",
      "assurer l'édition, la reprographie et le façonnage des documents",
      "élaborer et gérer les supports de traitement informatique des examens d'État et des concours",
      "assurer la gestion de la mémoire documentaire du ministère et alimenter le site web du ministère",
      "contribuer au choix de la technologie de pointe en matière de gestion électronique des documents et archives",
    ],
    "bureau de l'archivage électronique et de la diffusion de l'information": [46,
      "centraliser la documentation électronique des autres structures du ministère",
      "mettre à la disposition du ministère, les informations nécessaires à la promotion du système éducatif",
      "publier les produits documentaires en vue de susciter la recherche",
      "procéder à la dématérialisation des documents physiques du ministère",
      "assurer la conservation des documents numérisés",
      "faciliter l'accès et l'exploitation des archives",
    ],
    "service de la communication": [47,
      "assurer la visibilité communicationnelle du ministère",
      "promouvoir la communication digitale",
      "réaliser le référencement et le catalogue des périodiques",
      "participer à la définition de la stratégie de la communication digitale",
    ],
    "bureau de collecte des ressources numériques": [49,
      "gérer le répertoire des ressources numériques",
      "participer au suivi des abonnements périodiques",
      "participer à la gestion du paramétrage acquisition / périodique",
    ],
    "bureau de la communication en ligne": [50,
      "contribuer à la visibilité du ministère",
      "produire les contenus numériques",
      "gérer le site web",
      "gérer les relations avec les prestataires web",
    ],
    "service des finances et du matériel": [51,
      "élaborer et exécuter le budget des opérations de traitement informatique des examens d'État et des concours",
      "gérer les finances",
      "préparer et suivre l'approvisionnement du matériel informatique et accessoires des examens d'État et concours techniques et professionnels",
      "gérer le stock du matériel et d'équipement de la direction",
      "gérer le fichier de stock des équipements informatiques et accessoires des différents systèmes d'information du ministère",
    ],
    "bureau des finances": [53,
      "préparer les éléments du budget des opérations de traitement informatique des examens d'État et concours techniques et professionnels",
      "élaborer les états financiers",
      "exécuter les dépenses de la direction",
      "préparer les justificatifs de dépenses",
    ],
    "bureau du matériel": [54,
      "préparer et suivre l'approvisionnement des équipements informatiques des différents systèmes d'information et de communication du ministère",
      "mettre à jour le fichier de stock du matériel de la direction",
      "élaborer le fichier de gestion de stock du matériel, des équipements informatiques et accessoires des différents systèmes d'information du ministère",
    ],
    "direction de la coopération et du partenariat": [55,
      "concevoir et mettre en œuvre les stratégies de coopération dans les domaines de l'enseignement technique et professionnel",
      "promouvoir le partenariat avec les organismes spécialisés dans les domaines de l'enseignement technique et professionnel",
      "participer à l'élaboration des programmes de coopération dans le cadre de la mise en œuvre des conventions, des accords et protocoles d'accord de partenariat",
      "identifier et promouvoir les actes de coopération bilatérale et multilatérale relevant du ministère",
      "participer à la définition des méthodologies, des mécanismes de suivi et de contrôle des programmes de coopération",
      "préparer les dossiers des commissions mixtes",
      "assurer le suivi et l'évaluation des programmes de coopération et des accords de partenariat",
      "rechercher les financements nécessaires à la mise en œuvre des projets et programmes de coopération et des accords de partenariat",
    ],
    "service de la coopération bilatérale": [57,
      "assurer la veille de la coopération bilatérale",
      "identifier et promouvoir les actes de coopération bilatérale relevant du ministère",
      "rechercher et coordonner les appuis des partenaires, en vue de réaliser les projets du ministère",
      "préparer la participation de la République du Congo aux sessions des grandes commissions mixtes de coopération et aux réunions avec les partenaires bilatéraux dans les domaines de l'enseignement technique et professionnel",
      "veiller à la mise en œuvre des décisions issues des grandes commissions mixtes de coopération et aux réunions paritaires dans les domaines de l'enseignement technique et professionnel",
      "assurer le suivi et l'évaluation des projets et des accords de coopération dans les domaines de l'enseignement technique et professionnel",
    ],
    "bureau de la coopération afrique": [59,
      "assurer la veille de la coopération bilatérale Afrique",
      "suivre et analyser l'évolution de l'enseignement technique et professionnel en Afrique",
      "promouvoir et développer les relations de coopération en matière d'enseignement technique et professionnel en Afrique",
      "préparer, évaluer et suivre les conclusions des commissions africaines en matière d'enseignement technique et professionnel",
      "préparer la participation du Congo aux réunions des pays africains sur les questions liées à l'enseignement technique et professionnel",
      "participer à la préparation des dossiers à présenter lors des grandes commissions mixtes de coopération",
      "négocier les offres de bourses d'études des bacheliers de l'enseignement technique et professionnel, ainsi que pour la formation des formateurs",
      "préparer la participation de la République du Congo aux réunions, conférences et séminaires dans les domaines de l'enseignement technique et professionnel",
    ],
    "bureau de la coopération europe-asie-amérique-océanie": [60,
      "assurer la veille de la coopération bilatérale Europe-Asie-Amérique-Océanie",
      "suivre l'évolution des parcours de formation des apprenants ayant bénéficié de la bourse interne ou externe de l'enseignement technique et professionnel",
      "participer à la promotion et au développement de la coopération en matière d'enseignement technique et professionnel entre le Congo et les pays d'Europe, d'Asie, d'Amérique et d'Océanie",
      "suivre la mise en œuvre et faire l'évaluation des décisions et recommandations prises lors des réunions du Congo avec les pays d'Europe, d'Asie, d'Amérique et d'Océanie dans les domaines de l'enseignement technique et professionnel",
      "négocier les offres de bourses d'études des bacheliers du ministère, ainsi que pour la formation des formateurs dans les pays d'Europe, d'Asie, d'Amérique et d'Océanie",
      "préparer la participation de la République du Congo aux réunions, conférences et séminaires dans les domaines de l'enseignement technique et professionnel",
    ],
    "service de la coopération multilatérale": [61,
      "assurer la veille de la coopération multilatérale",
      "identifier et promouvoir les actes de coopération multilatérale relevant du ministère de l'enseignement technique et professionnel",
      "rechercher les appuis des partenaires multilatéraux, en vue de réaliser les projets du ministère de l'enseignement technique et professionnel",
      "préparer et participer, dans les domaines de l'enseignement technique et professionnel, aux sessions des grandes commissions mixtes de coopération et aux réunions avec les partenaires multilatéraux",
      "veiller à la mise en œuvre des conclusions des réunions avec les partenaires, des décisions issues des grandes commissions mixtes de coopération multilatérale et aux réunions paritaires",
      "assurer le suivi et l'évaluation des projets et des accords de coopération multilatérale",
    ],
    "bureau de l'organisation des nations unies (onu) et des institutions spécialisées": [63,
      "veiller à la contribution du Congo aux efforts des institutions spécialisées de l'ONU dans la modernisation de l'enseignement technique et professionnel",
      "suivre, analyser et faire appliquer les politiques des institutions spécialisées de l'ONU en matière d'enseignement technique et professionnel",
      "promouvoir la coopération multilatérale dans les domaines de l'enseignemen technique et professionnel",
    ],
    "bureau de l'organisation internationale de la francophonie": [64,
      "suivre et analyser les activités de la francophonie en matière de l'enseignement technique et professionnel",
      "veiller à la participation de la République du Congo pour le compte du ministère de l'enseignement technique et professionnel aux réunions des organes et des institutions de la francophonie",
    ],
    "service du partenariat": [65,
      "promouvoir la politique des partenariats au sein du ministère de l'enseignement technique et professionnel avec les organes spécialisés de l'Organisation des Nations Unies et les organisations non gouvernementales",
      "promouvoir et encourager le partenariat entre le ministère de l'enseignement technique et professionnel et le secteur public et privé",
    ],
    "bureau du partenariat public-privé": [67,
      "promouvoir la politique du partenariat au ministère de l'enseignement technique et professionnel",
      "préparer la participation du ministère de l'enseignement technique et professionnel à toutes les réunions de partenariat",
    ],
    "bureau du partenariat avec les organismes spécialisés et les organisations non gouvernementales (ong)": [68,
      "préparer la participation du ministère de l'enseignement technique et professionnel aux réunions relatives aux partenariats avec les organismes spécialisés et les ONG",
      "suivre et analyser les conclusions des conférences intergouvernementales relatives aux partenariats du développement",
    ],
    "direction des établissements privés de l'enseignement technique et professionnel": [69,
      "veiller à l'application des lois et règlements relatifs à l'exercice privé de l'enseignement",
      "examiner les demandes de création, d'ouverture, d'agrément et de fonctionnement des établissements privés de l'enseignement technique et professionnel",
      "assurer le suivi administratif et pédagogique des structures privées de l'enseignement",
      "veiller au bon fonctionnement et à la qualité des formations dispensées dans les établissements privés",
      "veiller à la disponibilité, dans les établissements privés, des ressources humaines de qualité et des matériels adéquats",
      "formuler des avis et suggestions dans les domaines de l'enseignement technique et professionnel privé en matière de création, d'ouverture, d'extension et de fermeture des structures privées de l'enseignement",
      "préparer et organiser les travaux de la commission d'agrément, de création, d'ouverture et de fonctionnement des structures privées de l'enseignement",
      "tenir à jour le fichier et les dossiers individuels des établissements privés de l'enseignement technique et professionnel",
    ],
    "service du contrôle des établissements privés de l'enseignement technique et professionnel": [71,
      "veiller au respect et à l'application de la réglementation en vigueur dans le domaine de l'enseignement technique et professionnel",
      "suivre les activités des établissements privés de l'enseignement technique et professionnel",
      "exploiter et analyser les rapports et en faire la synthèse",
      "mettre à jour la cartographie des établissements privés de l'enseignement technique et professionnel et les statistiques du personnel et des apprenants",
      "participer à l'organisation et à la tenue des sessions de la commission nationale d'agrément",
    ],
    "bureau du contrôle et de l'orientation": [73,
      "veiller au respect et à l'application de la réglementation en vigueur dans le domaine de l'enseignement technique et professionnel",
      "suivre les activités des établissements privés de l'enseignement technique et professionnel",
      "contrôler la conformité des structures physiques des établissements privés de l'enseignement technique et professionnel",
      "mettre à jour la cartographie des établissements privés de l'enseignement technique et professionnel",
      "suivre et faire appliquer les décisions de la commission nationale d'agrément",
    ],
    "bureau des réformes des établissements privés de l'enseignement technique et professionnel": [74,
      "proposer des réformes relatives à l'enseignement privé technique et professionnel",
      "exploiter et analyser les rapports et autres documents administratifs des établissements privés de l'enseignement technique et professionnel",
      "examiner les dossiers des postulants à l'enseignement dans les établissements privés de l'enseignement technique et professionnel",
      "préparer et participer à l'organisation et à la tenue de la commission nationale d'agrément",
      "mettre à jour les statistiques du personnel et des apprenants des établissements privés de l'enseignement technique et professionnel",
    ],
    "service du contrôle des établissements privés de l'enseignement technique et professionnel > bureau du contentieux": [75,
      "recevoir toute requête relative aux contestations",
      "gérer le contentieux",
    ],
    "service des agréments": [76,
      "exploiter et analyser les documents de création, d'ouverture, de modification et de fermeture des établissements privés de l'enseignement technique et professionnel",
      "préparer les dossiers à soumettre à la commission nationale d'agrément",
      "élaborer les projets de texte d'octroi d'agrément aux établissements privés de l'enseignement technique et professionnel",
      "préparer et participer à l'organisation et à la tenue des sessions de la commission nationale d'agrément",
      "vulgariser la réglementation relative aux établissements privés de l'enseignement technique et professionnel",
      "notifier aux établissements les résultats de la commission nationale d'agrément",
      "suivre les inscriptions et les résultats des candidats des établissements privés de l'enseignement technique et professionnel aux différents examens d'État",
    ],
    "bureau de l'analyse et de l'agrément": [78,
      "élaborer les projets de texte d'octroi d'agrément aux établissements privés de l'enseignement technique et professionnel",
      "analyser les documents de création, d'ouverture et de fermeture des établissements privés de l'enseignement technique et professionnel",
      "participer à l'organisation et à la tenue des sessions de la commission nationale d'agrément",
      "suivre les inscriptions et les résultats des examens des apprenants des établissements privés de l'enseignement technique et professionnel",
    ],
    "bureau de la documentation et de la diffusion de l'information": [79,
      "vulgariser la réglementation relative aux établissements privés de l'enseignement technique et professionnel",
      "préparer les dossiers à soumettre à la commission nationale d'agrément",
      "participer à la commission nationale d'agrément",
    ],
    "direction de la lutte contre la fraude, la corruption, la violence et autres pratiques répréhensibles en milieu scolaire": [80,
      "concevoir et mettre en œuvre les politiques et les stratégies d'éradication de la fraude, la corruption, la violence et autres pratiques répréhensibles en milieu scolaire",
      "lutter contre toute sorte de fraude, de corruption, de violence et autres pratiques répréhensibles en milieu scolaire",
      "veiller au respect des procédures d'inscription des candidats aux examens d'État et aux concours techniques et professionnels",
      "veiller à la régularité de toutes les opérations liées à la préparation, à l'organisation, au déroulement et à la publication des résultats des examens et concours de l'enseignement technique et professionnel",
    ],
    "service des stratégies, du suivi et du contrôle": [82,
      "élaborer et promouvoir les stratégies et politiques efficientes susceptibles de lutter contre la corruption, les violences et autres pratiques répréhensibles en milieu scolaire",
      "analyser et prospecter les stratégies et politiques envisageables contre la corruption, les violences et autres pratiques répréhensibles en milieu scolaire",
      "coordonner et suivre la mise en œuvre des stratégies et politiques adoptées",
      "évaluer l'effectivité et l'efficacité des stratégies et politiques contre la fraude, la corruption, les violences et autres pratiques répréhensibles en milieu scolaire",
      "établir des rapports périodiques sur l'efficience et l'efficacité des stratégies et politiques contre la fraude, la corruption, les violences et autres pratiques répréhensibles en milieu scolaire",
    ],
    "bureau des stratégies": [84,
      "diagnostiquer et analyser les phénomènes de fraude, de corruption, de violences et autres pratiques répréhensibles en milieu scolaire",
      "définir et choisir les options suivant le triptyque : prospective-stratégie management des hommes",
      "participer à l'élaboration des plans stratégiques et politiques de lutte contre les phénomènes de fraude, de corruption, de violences et autres pratiques répréhensibles en milieu scolaire",
      "appliquer les méthodes classiques ou innovantes et rigoureuses aux questions de fraude, de corruption, de violences et autres pratiques répréhensibles en milieu scolaire",
      "créer et gérer une banque de données périodiques sur l'efficience et l'efficacité des stratégies et politiques contre la fraude, la corruption, les violences et autres pratiques répréhensibles en milieu scolaire",
    ],
    "bureau du suivi et du contrôle": [85,
      "veiller à l'accomplissement des objectifs et politiques d'action dans le cadre de la lutte contre la fraude, la corruption, les violences et autres pratiques répréhensibles en milieu scolaire",
      "évaluer les options stratégiques et politiques de lutte et leur incidence sur les phénomènes de fraude, de corruption, de violences et autres pratiques répréhensibles en milieu scolaire",
      "contrôler l'effectivité et l'efficacité des activités des délégués de lutte contre la fraude, la corruption, les violences et autres pratiques répréhensibles",
    ],
    "service de la lutte contre la fraude et la corruption en milieu scolaire": [86,
      "appliquer toutes stratégies et politiques mises ou à mettre en oeuvre dans la lutte contre la fraude et/ou la corruption en milieu scolaire",
      "gérer le contentieux disciplinaire scolaire en cas de fraude et/ou de corruption en milieu scolaire",
      "établir une base de données périodiques des cas de fraude et/ou de corruption enregistrées et des procédures judiciaires à l'encontre de leurs auteurs",
      "établir des rapports périodiques des cas de fraude enregistrés et engager des procédures disciplinaires et judiciaires à l'encontre de leurs auteurs",
    ],
    "bureau de la lutte contre la fraude": [88,
      "impulser l'ensemble des processus d'éradication des faits de fraude en milieu scolaire",
      "procéder à des enquêtes dans le cadre des dénonciations sur les faits de fraude, pendant les évaluations dans les établissements d'enseignement technique et professionnel, les inscriptions et le déroulement des examens et concours techniques et professionnels",
      "établir des rapports périodiques des cas de fraudes enregistrées et engager des procédures disciplinaires et judiciaires à l'encontre de leurs auteurs",
    ],
    "bureau de la lutte contre la corruption": [89,
      "analyser le contentieux disciplinaire scolaire et enquêter sur tous les faits de corruption dénoncés pendant les évaluations dans les établissements d'enseignement technique et professionnel, les inscriptions et le déroulement des différents examens et concours techniques et professionnels",
      "préparer toutes procédures en vue de la saisine des instances judiciaires pour les cas avérés de corruption",
      "participer à l'établissement des rapports périodiques des cas de corruption enregistrés et engager des procédures disciplinaires et judiciaires",
    ],
    "service de la lutte contre la violence et autres pratiques répréhensibles en milieu scolaire": [90,
      "organiser un cadre d'application des règles de conduite et de lutte contre les violences et les pratiques répréhensibles en milieu scolaire",
      "assurer la gestion du contentieux par des enquêtes sur les faits de violences et pratiques répréhensibles dans les établissements d'enseignement technique et professionnel, lors des inscriptions et du déroulement des examens et concours techniques et professionnels",
      "préparer toutes procédures en vue de la saisine des instances judiciaires pour les cas avérés de violences et/ou de pratiques répréhensibles",
      "constituer la base de données périodique des cas de violences et des pratiques répréhensibles avérés et engager des procédures disciplinaires et judiciaires à l'encontre de leurs auteurs",
    ],
    "bureau de la lutte contre les violences en milieu scolaire": [92,
      "lutter contre les violences en milieu scolaire en appliquant toutes stratégies et politiques adoptées par le ministère",
      "organiser et manager le contentieux disciplinaire et judiciaire des cas de violences, pendant les évaluations dans les établissements d'enseignement professionnel, les inscriptions et le déroulement des examens et concours techniques et professionnels",
      "établir des rapports périodiques des cas de violences enregistrés et engager des procédures disciplinaires et judiciaires à l'encontre de leurs auteurs",
    ],
    "bureau de la lutte contre les pratiques répréhensibles en milieu scolaire": [93,
      "organiser en application des stratégies et politiques élaborées pour lutter contre toute pratique répréhensible, à savoir notamment : le tribalisme, le régionalisme, le sectarisme, la discrimination physique et sociale en milieu scolaire",
      "connaitre du contentieux disciplinaire sur les faits de pratiques répréhensibles pendant les évaluations dans les établissements d'enseignement professionnel, les inscriptions et le déroulement des différents examens et concours techniques et professionnels",
      "connaitre du contentieux des cas de pratiques répréhensibles en milieu scolaire",
      "établir des rapports périodiques des pratiques répréhensibles enregistrés et engager les procédures disciplinaires et judiciaires",
    ],
    "cellule de gestion des marchés publics": [94,
    ],
    "unité de coordination des projets": [95,
    ],
  },
};
