import type { AttributionsParTexte } from "./socle";

/**
 * Les services déconcentrés — arrêtés n° 25570, 25571 et 25572.
 *
 * Transcrit du Journal officiel, article par article. Les intitulés sont
 * ceux du texte : c'est par eux que l'entité est retrouvée.
 */
export const DECONCENTRATION: AttributionsParTexte = {
  "25570": {
    "secrétariat > secrétariat": [5,
      "réceptionner et expédier le courrier",
      "analyser les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "veiller au suivi du programme journalier, hebdomadaire et mensuel de l'inspecteur coordonnateur interdépartemental",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "service des finances et du matériel > service des finances et du matériel": [6,
      "collecter les données budgétaires",
      "élaborer l'avant-projet de budget de l'inspection interdépartementale et en assurer le suivi et la gestion",
      "préparer les engagements des crédits autorisés",
      "centraliser les besoins en matériels et équipements exprimés par les services des l'inspection interdépartementale",
      "acquérir le matériel et les équipements de l'inspection interdépartementale, en assurer la gestion et le contrôle",
      "collecter les contributions des établissements publics et privés relatives à l'organisation des activités pédagogiques et aux évaluations",
    ],
    "service du personnel, des statistiques, des archives et de la documentation > service du personnel, des statistiques, des archives et de la documentation": [7,
      "gérer les situations administratives du personnel",
      "centraliser les besoins en personnel de l'inspection interdépartementale",
      "tenir le fichier et les dossiers du personnel de l'inspection interdépartementale",
      "veiller au règlement du contentieux",
      "recevoir, inventorier, répertorier, classer et conserver les documents",
      "constituer et gérer les archives",
      "tenir à jour les statistiques du personnel et des apprenants",
      "diffuser les informations",
    ],
    "la division pédagogique > division pédagogique": [8,
      "assurer l'encadrement et le contrôle pédagogique",
      "effectuer des missions d'inspection, de contrôle et d'évaluation dans les structures scolaires",
      "participer à la conception des supports didactiques",
      "rédiger les rapports d'inspection pédagogique dans les établissements scolaires",
      "impulser et promouvoir les politiques et innovations pédagogiques",
      "tenir à jour le fichier, les dossiers et les statistiques du personnel enseignant et de la population scolaire",
      "participer à l'organisation et à la supervision des évaluations",
      "analyser et évaluer les résultats scolaires",
      "contrôler la régularité des inscriptions des candidats aux examens d'État et concours techniques et professionnels",
      "contrôler la régularité des dossiers relatifs aux demandes de bourses et des aides scolaires formulées par les établissements scolaires",
    ],
    "la division des affaires administratives et des ressources humaines > division des affaires administratives et des ressources humaines": [9,
      "veiller à la bonne gestion du personnel",
      "mettre à jour le fichier du personnel, les dossiers individuels et les statistiques",
      "participer au mouvement du personnel",
      "assurer le contrôle administratif du personnel et des services",
      "analyser et évaluer les rapports en provenance des établissements scolaires et des inspections",
      "participer à l'élaboration et à l'exécution des plans de formation du personnel",
      "veiller au perfectionnement et au recyclage des agents en cours d'activité",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "la division du management et de l'assurance qualité > division du management et de l'assurance qualité": [10,
      "vulgariser les méthodes et les outils du management de la formation incluant la stratégie, l'ingénierie de formation, la réglementation, le financement des actions de formation, les pédagogies différentielles",
      "évaluer les besoins en formation du personnel",
      "participer à la mise en place des dispositifs de l'ingénierie de formation",
      "appliquer les procédures garantissant la qualité de l'enseignement technique et professionnel",
      "participer à la formation du personnel aux méthodes qualité",
      "et, d'une manière générale, exécuter toute tâche qui peut lui être confiée",
    ],
    "la division des finances, de l'équipement et du patrimoine > division des finances, de l'équipement et du patrimoine": [11,
      "assurer l'encadrement des gestionnaires des structures scolaires",
      "contrôler la gestion des subventions, des crédits alloués, des bourses scolaires et de toute contribution accordée aux établissements scolaires publics",
      "analyser les rapports financiers en provenance des structures scolaires",
      "vulgariser les supports de contrôle de gestion en matière financière, d'équipement et de patrimoine",
      "assurer le contrôle de la gestion du patrimoine",
      "vulgariser les mesures susceptibles d'améliorer la gestion des finances et du patrimoine du ministère",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "secrétariat": [14,
      "réceptionner et expédier le courrier",
      "analyser les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "veiller au suivi du programme journalier, hebdomadaire et mensuel de l'inspecteur chef d'antenne départementale d'encadrement et de contrôle",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "service des finances et du matériel": [15,
      "centraliser les besoins en matériels et équipements exprimés par les services de l'antenne départementale d'encadrement et de contrôle, en assurer la gestion, la maintenance et le suivi",
      "participer à l'élaboration de l'avant-projet de budget de l'antenne départementale d'encadrement et de contrôle, et en assurer l'exécution",
      "gérer les finances et le matériel de l'antenne départementale d'encadrement et de contrôle",
      "collecter les contributions des établissements publics et privés relatives à l'organisation des activités pédagogiques et aux évaluations",
    ],
    "service du personnel, des statistiques, des archives et de la documentation": [16,
      "gérer les situations administratives du personnel de l'antenne départementale d'encadrement et de contrôle",
      "centraliser les besoins en personnel de l'inspection départementale",
      "tenir à jour le fichier et les dossiers du personnel de l'antenne départementale d'encadrement et de contrôle",
      "tenir à jour les statistiques",
      "veiller au règlement du contentieux du personnel de l'antenne départementale d'encadrement et de contrôle",
      "constituer et gérer la documentation",
      "élaborer le fichier de suivi de la population scolaire",
    ],
    "division pédagogique": [17,
      "assurer l'encadrement et le contrôle pédagogique",
      "effectuer des missions d'inspection, de contrôle et d'évaluation dans les structures scolaires",
      "rédiger les rapports d'inspection pédagogique dans les établissements scolaires",
      "tenir à jour le fichier, les dossiers et les statistiques du personnel enseignant et de la population scolaire",
      "participer à l'organisation et à la supervision des évaluations",
      "analyser et évaluer les résultats scolaires",
      "contrôler la régularité des inscriptions des candidats aux examens d'État et concours techniques et professionnels",
      "participer au déroulement des examens d'État et concours",
      "contrôler la régularité des dossiers relatifs aux demandes de bourses et des aides scolaires formulées par les établissements scolaires",
    ],
    "division des affaires administratives et des ressources humaines": [18,
      "assurer la gestion du personnel enseignant et administratif",
      "tenir à jour le fichier, les dossiers individuels et les statistiques du personnel administratif et enseignant",
      "participer au mouvement du personnel administratif et enseignant",
      "analyser et évaluer les rapports administratifs en provenance des établissements scolaires",
      "participer à l'élaboration et à l'exécution des plans de formation des personnels administratif et enseignant",
      "veiller au perfectionnement et au recyclage des agents en cours d'activité",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "division du management et de l'assurance qualité": [19,
      "vulgariser les méthodes et les outils du management de la formation incluant la stratégie, l'ingénierie de formation, la réglementation, le financement des actions de formation, les pédagogies différentielles",
      "évaluer les besoins en formation du personnel",
      "participer à la mise en place des dispositifs de l'ingénierie de formation",
      "appliquer les procédures garantissant la qualité de l'enseignement technique et professionnel",
      "participer à la formation du personnel aux méthodes qualité",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "division des finances, de l'équipement et du patrimoine": [20,
      "assurer l'encadrement des gestionnaires des structures scolaires",
      "contrôler la gestion des subventions, des crédits alloués, des bourses scolaires et de toute contribution accordée aux établissements scolaires publics",
      "analyser les rapports financiers en provenance des structures scolaires",
      "rédiger les rapports d'inspection financière dans les établissements scolaires",
      "vulgariser les supports de contrôle de gestion en matière financière, d'équipement et de patrimoine",
      "assurer le contrôle de la gestion du patrimoine",
      "vulgariser les mesures susceptibles d'améliorer la gestion des finances et du patrimoine du ministère",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
  },
  "25571": {
    "directions départementales de l'enseignement technique": [2,
      "participer à la coordination des activités du ministère",
      "dresser et orienter les rapports à l'endroit des directeurs généraux en fonction des attributions",
      "veiller à l'application de la réglementation en vigueur relative à l'exercice de l'enseignement technique",
      "mettre à jour le fichier des établissements publics et privés de l'enseignement technique",
      "préparer le budget de la direction départementale",
      "préparer la rentrée scolaire des établissements techniques",
      "préparer les dossiers d'agrément, de création et d'ouverture des établissements privés de l'enseignement technique",
      "préparer conjointement avec l'inspection interdépartementale l'organisation des examens et des concours d'entrée dans les établissements d'enseignement technique",
      "tenir à jour les statistiques des activités départementales",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "secrétariat": [4,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "service des finances et du matériel": [5,
      "préparer le budget de la direction départementale et suivre son exécution",
      "gérer les finances",
      "gérer les crédits relatifs aux missions et aux titres de transports",
      "préparer les dossiers de payement des émoluments relatifs aux prestations du personnel vacataire et tous les autres types de prestations de la direction départementale",
      "collecter les frais d'inscription aux examens d'État et concours techniques",
      "gérer le matériel de la direction départementale",
      "gérer les œuvres scolaires dans les établissements d'enseignement technique",
      "assurer les aides scolaires dans les établissements d'enseignement technique",
    ],
    "service des examens et concours techniques": [6,
      "recevoir, contrôler et préparer les dossiers des candidats aux différents examens et concours techniques",
      "participer à l'organisation et au déroulement des différents examens et concours techniques",
      "délivrer les diplômes et les certificats sanctionnant la fin des formations de l'enseignement technique",
      "recevoir et gérer les réclamations",
    ],
    "service de l'administration et des ressources humaines": [7,
      "gérer les affaires administratives de la direction départementale",
      "appliquer la politique du minisière en matière de gestion des ressources humaines",
      "gérer le personnel de la direction départementale",
      "connaitre du contentieux relatif au personnel de la direction départementale",
      "gérer l'orientation scolaire dans les établissements d'enseignement technique",
      "assurer le suivi de la scolarité des élèves dans les établissements d'enseignement technique",
    ],
    "service de l'enseignement technique": [8,
      "veiller à l'application de la réglementation relative à l'enseignement technique",
      "veiller à la qualité des enseignements dispensés dans les établissements d'enseignement technique",
      "participer à l'organisation des examens et des concours d'entrée dans les établissements d'enseignement technique",
      "mettre à jour le fichier des établissements publics et privés de l'enseignement technique",
      "tenir à jour les statistiques des établissements techniques",
      "participer à la mise en œuvre des curricula, des méthodes et techniques pédagogiques et en assurer le suivi",
      "participer à la gestion du mouvement du personnel en fonction des besoins",
    ],
    "service de l'équipement et du patrimoine": [9,
      "appliquer la politique du ministère en matière de gestion des équipements et du patrimoine",
      "participer à la veille de l'immatriculation des immeubles du ministère",
      "participer à la gestion de l'équipement et du patrimoine du ministère",
      "assurer la gestion des stocks et le dispatching",
      "tenir à jour les statistiques",
      "veiller à la sécurisation des sites",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
  },
  "25572": {
    "directions départementales de l'enseignement professionnel": [2,
      "participer à la coordination des activités du ministère",
      "dresser et orienter les rapports à l'endroit des directeurs généraux en fonction des attributions",
      "veiller à l'application de la réglementation en vigueur relative à l'exercice de l'enseignement professionnel",
      "mettre à jour le fichier des établissements publics et privés de l'enseignement professionnel",
      "préparer le budget de la direction départementale",
      "préparer la rentrée scolaire des établissements professionnels",
      "préparer les dossiers d'agrément de création et d'ouverture des établissements privés de l'enseignement professionnel",
      "préparer conjointement avec l'inspection interdépartementale l'organisation des examens et des concours d'entrée dans les établissements d'enseignement professionnel",
      "tenir à jour les statistiques des activités départementales",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "secrétariat": [4,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "service des finances et du matériel": [5,
      "préparer le budget de la direction départementale et suivre son exécution",
      "gérer les finances",
      "gérer les crédits relatifs aux missions et aux titres de transports",
      "préparer les dossiers de payement des émoluments relatifs aux prestations du personnel vacataire et tous les autres types de prestations de la direction départementale",
      "collecter les frais d'inscription aux examens d'État et concours professionnels",
      "gérer le matériel de la direction départementale",
      "gérer les œuvres scolaires dans les établissements d'enseignement professionnel",
      "assurer les aides scolaires dans les établissements d'enseignement professionnel",
    ],
    "service des examens et concours professionnels": [6,
      "recevoir, contrôler et préparer les dossiers des candidats aux différents examens et concours professionnels",
      "participer à l'organisation et au déroulement des différents examens et concours professionnels",
      "délivrer les diplômes et les certificats sanctionnant la fin des formations de l'enseignement professionnel",
      "recevoir et gérer les réclamations",
    ],
    "service de l'administration et des ressources humaines": [7,
      "gérer les affaires administratives de la direction départementale",
      "appliquer la politique du ministère en matière de gestion des ressources humaines",
      "gérer le personnel de la direction départementale",
      "connaître du contentieux relatif au personnel de la direction départementale",
      "gérer l'orientation scolaire dans les établissements d'enseignement professionnel",
      "assurer le suivi de la scolarité des élèves dans les établissements d'enseignement professionnel",
    ],
    "service de l'enseignement professionnel": [8,
      "veiller à l'application de la réglementation relative à l'enseignement professionnel",
      "veiller à la qualité des enseignements dispensés dans les établissements d'enseignement professionnel",
      "participer à l'organisation des examens et des concours d'entrée dans les établissements d'enseignement professionnel",
      "mettre à jour le fichier des établissements publics et privés de l'enseignement professionnel",
      "tenir à jour les statistiques des établissements professionnels",
      "participer à la mise en œuvre des curricula, des méthodes et techniques pédagogiques et en assurer le suivi",
      "participer à la gestion du mouvement du personnel en fonction des besoins",
    ],
    "service de l'équipement et du patrimoine": [9,
      "appliquer la politique du ministère en matière de gestion des équipements et du patrimoine",
      "participer à la veille de l'immatriculation des immeubles du ministère",
      "participer à la gestion de l'équipement et du patrimoine du ministère",
      "assurer la gestion des stocks et le dispatching",
      "tenir à jour les statistiques",
      "veiller à la sécurisation des sites",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
  },
};
