import type { AttributionsParTexte } from "./socle";

/**
 * La direction générale de l'administration et des ressources humaines — arrêté n° 25567.
 *
 * Transcrit du Journal officiel, article par article. Les intitulés sont
 * ceux du texte : c'est par eux que l'entité est retrouvée.
 */
export const DGARH: AttributionsParTexte = {
  "25567": {
    "secrétariat de direction": [3,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "bureau du courrier, des relations publiques et de la communication": [5,
      "réceptionner, enregistrer et communiquer le courrier",
      "expédier et diffuser tout document administratif",
      "analyser sommairement les correspondances et autres documents administratifs",
      "assurer le suivi du courrier",
      "assurer la diffusion et la circulation des informations en interne et en externe de la direction générale",
      "assurer les relations publiques de la direction générale",
    ],
    "bureau de la saisie et de la reprographie": [6,
      "saisir et reprographier les correspondances et autres documents administratifs",
      "assurer le traitement informatique des données administratives",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "direction du personnel, de la condition enseignante et de la formation": [7,
      "assurer la gestion du personnel administratif et enseignant du ministère",
      "organiser le mouvement des personnels administratifs et enseignants en collaboration avec les autres directions générales",
      "suivre les dossiers de recrutement, la gestion des carrières et la promotion du personnel administratif et des enseignants",
      "assurer et promouvoir la formation du personnel administratif et enseignant",
      "gérer les questions liées à la condition enseignante",
      "gérer le contentieux lié au personnel",
      "assurer la performance des conditions enseignantes",
    ],
    "service du personnel et du contentieux": [9,
      "assurer le suivi de la carrière administrative du personnel du ministère",
      "participer à la mise en œuvre du mouvement du personnel du ministère",
      "veiller à la formation du personnel du ministère",
      "gérer le contentieux",
      "suivre les dossiers de recrutement",
      "assurer le suivi des positions administratives du personnel du ministère",
    ],
    "bureau du recrutement et du mouvement du personnel": [11,
      "publier les appels à candidature",
      "recevoir et sélectionner les dossiers de recrutement",
      "suivre le mouvement du personnel du ministère",
      "initier le planning de recrutement et du mouvement du personnel",
      "assurer la communication en matière de recrutement et de mouvement du personnel",
      "centraliser et gérer les fichiers et dossiers individuels du personnel",
      "collecter les actes de détachement",
      "mettre à jour les registres de recrutement et de mouvement du personnel pour comptabilisation",
    ],
    "bureau de la gestion de la carrière administrative": [12,
      "préparer les dossiers à soumettre à la commission administrative paritaire de gestion des carrières administratives",
      "initier les textes portant admission ou ajournement aux différents examens pratiques de titularisation",
      "participer au suivi de la carrière du personnel du ministère",
      "maintenir un contact permanent avec les services internes et externes impliqués dans le suivi de la carrière administrative",
      "mettre à jour un fichier informatisé",
    ],
    "bureau du contentieux": [13,
      "recevoir toutes contestations relatives au personnel",
      "gérer le contentieux",
    ],
    "service de la condition enseignante": [14,
      "veiller à l'effectivité de la condition enseignante",
      "travailler sur le statut des enseignants",
      "initier les réformes sur les conditions de travail des enseignants",
      "gérer l'employabilité des enseignants",
      "organiser la célébration de la journée mondiale des enseignants",
      "veiller aux intérêts et situations des enseignants",
      "veiller à la performance des enseignants",
      "maintenir un contact permanent avec les partenaires sociaux",
    ],
    "bureau du suivi et évaluation de la condition enseignante": [16,
      "traiter et suivre les dossiers relatifs aux demandes, aux rétablissements et à la suspension des salaires, des primes et indemnités spécifiques du personnel",
      "identifier et actualiser les critères de performance des enseignants et produire les rapports y relatifs",
      "produire les rapports trimestriels et annuels relatifs aux performances du personnel enseignant, par département",
      "participer à l'organisation de la célébration de la journée mondiale des enseignants",
      "élaborer les tableaux d'honneur annuel des établissements sur la base des performances des enseignants",
    ],
    "bureau du suivi et évaluation des enseignants prestataires, volontaires et vacataires": [17,
      "suivre les situations administrative, financière et scolaire des enseignants prestataires, volontaires et vacataires",
      "élaborer les états de besoin en personnel prestataire, volontaire et vacataire sur la base des besoins exprimés par les établissements scolaires par l'intermédiaire des directions départementales",
      "produire les listes et tableaux statistiques des enseignants prestataires, volontaires et vacataires",
    ],
    "service de la formation": [18,
      "évaluer les besoins en formation",
      "concevoir et élaborer les plans de formation en fonction des besoins évalués",
      "identifier les écoles ou structures de formation habilitées pour la formation du personnel enseignant et administratif",
      "proposer des stages aux agents en fonction des besoins exprimés",
      "suivre le déroulement des stages des agents mis en formation dans les établissements de formation sur le plan national et international",
      "initier les autorisations de mise en stage, de formation et de concourir",
    ],
    "bureau de la formation du personnel enseignant": [20,
      "évaluer les besoins en formation du personnel enseignant",
      "concevoir et élaborer les plans de formation du personnel enseignant en fonction des besoins évalués",
      "identifier les écoles ou structures de formation habilitées pour la formation du personnel enseignant",
      "organiser les séminaires et conférences pédagogiques du personnel enseignant",
      "suivre le déroulement des stages de formation du personnel enseignant dans les établissements de formation sur le plan national et international",
      "initier les autorisations de mise en stage, de formation et de concourir du personnel enseignant",
    ],
    "bureau de la formation du personnel administratif et technique": [21,
      "évaluer les besoins en formation des personnels administratif et technique",
      "concevoir et élaborer les plans de formation du personnel administratif et technique en fonction des besoins exprimés",
      "identifier les écoles ou structures de formation habilitées pour la formation des personnels administratif et technique",
      "initier et proposer des séminaires et conférences de performance des personnels administratif et technique",
      "suivre le déroulement des stages de formation des personnels administratif et technique dans les établissements de formation sur le plan national et international",
      "initier les autorisations de mise en stage, de formation et de concourir des personnels administratif et technique",
    ],
    "direction de l'orientation, des bourses et des aides scolaires": [22,
      "gérer l'orientation et les œuvres sociales",
      "superviser les campagnes ou salons d'orientation organisés par le ministère",
      "assurer le suivi de la scolarité des élèves",
      "gérer les bourses et les frais académiques des apprenants à l'intérieur et à l'extérieur du pays",
      "suivre les offres des bourses au niveau national et international",
      "assurer les aides scolaires",
      "tenir les statistiques en matière d'orientation, de bourse, de frais académiques et d'aides scolaires",
      "assurer le suivi sanitaire des élèves",
    ],
    "service de l'orientation": [24,
      "gérer l'orientation et les aides scolaires",
      "superviser les campagnes ou salons d'orientation organisés par le ministère",
      "traiter les questions liées à l'orientation des apprenants",
      "donner des avis en matière d'orientation",
      "assurer la gestion des conseillers et des attachés d'orientation",
      "assurer le suivi des apprenants orientés dans les différents établissements",
      "maintenir un contact permanent avec les partenaires de la formation technique et professionnelle pour une meilleure orientation",
    ],
    "bureau de l'information": [26,
      "assurer la communication en matière d'orientation",
      "assurer l'orientation des élèves",
      "maintenir un contact permanent avec les partenaires œuvrant dans le domaine de l'orientation scolaire",
      "gérer les données relatives à l'orientation des apprenants",
      "assurer la collecte des données statistiques en matière d'orientation",
      "initier les projets de textes relatifs à l'orientation des élèves",
    ],
    "bureau du suivi de la scolarité et des statistiques": [27,
      "élaborer le fichier des apprenants orientés",
      "analyser les dossiers des candidats aux bourses et aides scolaires",
      "suivre la scolarité des apprenants orientés avec la collaboration des établissements d'accueil",
      "mettre à jour les statistiques des orientations",
    ],
    "service des bourses": [28,
      "gérer les bourses",
      "centraliser les offres de bourses",
      "centraliser les demandes de bourses",
      "préparer les projets d'arrêté relatifs à l'attribution, au renouvellement, à la suspension et à la suppression des bourses",
      "identifier les cas sociaux et transmettre les dossiers y relatifs aux services compétents",
      "initier des contacts avec la direction de la coopération, auprès des partenaires de la formation technique et professionnelle, en vue de l'obtention des bourses",
    ],
    "service des bourses > bureau du traitement": [30,
      "recevoir les dossiers des boursiers",
      "dresser la liste des postulants",
      "assurer un traitement préliminaire",
      "préparer la tenue de la commission d'attribution, de renouvellement, de suspension et de suppression des bourses",
      "préparer les projets d'arrêté relatifs à l'attribution, au renouvellement, à la suspension et à la suppression des bourses",
    ],
    "service des bourses > bureau des réclamations": [31,
      "recevoir et traiter les réclamations relatives à la bourse",
      "procéder à toute constatation ou enquête utile",
    ],
    "service des aides sociales et scolaires": [32,
      "recevoir et traiter les demandes des aides scolaires et sociales",
      "participer à la préparation des projets d'arrêté relatifs à l'attribution, au renouvellement, à la suspension et à la suppression des bourses",
      "centraliser les offres des aides sociales et scolaires",
    ],
    "service des aides sociales et scolaires > bureau du traitement": [34,
      "recevoir les dossiers des aides scolaires",
      "dresser la liste des postulants aux aides scolaires",
      "assurer un traitement des demandes relatives aux aides sociales et scolaires",
      "diffuser toute information officielle relative aux aides scolaires",
    ],
    "service des aides sociales et scolaires > bureau des réclamations": [35,
      "recevoir les réclamations relatives aux aides sociales et scolaires",
      "traiter les réclamations relatives aux aides sociales et scolaires en collaboration avec les services internes ou externes impliqués dans le processus d'octroi des aides scolaires",
      "proposer à la hiérarchie toute hypothèse plausible",
      "procéder à toute constatation. ou enquête utile en vue d'en donner suite",
    ],
    "direction de l'administration, des finances et du matériel": [36,
      "gérer les affaires administratives",
      "gérer l'administration scolaire en corrélation avec les autres directions générales",
      "promouvoir l'information des administrations centrales et départementales",
      "coordonner les activités des centres de documentation informatique et les centres multimédias des établissements scolaires",
      "gérer et informatiser les archives et la documentation",
      "gérer les finances",
      "participer à l'élaboration du budget",
      "gérer le budget et la comptabilité",
      "gérer le matériel de la direction générale",
    ],
    "service des affaires administratives": [38,
      "gérer les ressources humaines de la direction générale",
      "suivre la gestion des carrières du personnel de la direction générale",
      "gérer les situations administratives de la direction générale",
    ],
    "bureau du personnel de la direction générale": [40,
      "mettre à jour les données statistiques du personnel de la direction générale",
      "déterminer les besoins et les déficits du personnel de la direction générale",
      "recevoir et centraliser les réclamations relatives à la gestion du personnel de la direction générale",
    ],
    "bureau des indemnités et des charges administratives": [41,
      "traiter les indemnités et primes du personnel de la direction générale",
      "suivre les dossiers relatifs aux primes et indemnités des charges administratives transmis au ministère des finances, du budget et du portefeuille public",
    ],
    "service des finances et du matériel": [42,
      "élaborer le projet de budget de la direction générale",
      "suivre l'exécution du budget de la direction générale",
      "assurer la gestion du matériel de la direction générale",
      "assurer la production du rapport périodique sur l'exécution du budget de la direction générale",
    ],
    "bureau des finances": [44,
      "collecter les données budgétaires",
      "élaborer l'avant-projet de budget de la direction générale",
      "préparer les engagements des crédits autorisés",
      "suivre l'exécution du budget de la direction générale",
      "gérer les bourses et les aides scolaires",
      "assurer le suivi des dossiers de vacation et de prestation",
      "tenir la comptabilité de la direction générale",
      "dresser les rapports financiers de la direction générale",
    ],
    "bureau du matériel": [45,
      "gérer le matériel de la direction générale",
      "gérer le stock, assurer le dispatching et l'acheminement du matériel",
      "recevoir et analyser les besoins des différentes structures",
      "mettre à jour le fichier informatisé du matériel de la direction générale",
    ],
    "service des archives et de la documentation": [46,
      "gérer les archives et la documentation de la direction générale",
      "constituer la mémoire physique et virtuelle de la direction générale",
      "travailler en étroite collaboration avec les services et projets du ministère",
      "recenser et numériser les textes administratifs du ministère",
      "transférer les fichiers numérisés au service des archivages et de la documentation à la direction des systèmes d'information et de la communication",
    ],
    "bureau des archives": [48,
      "collecter les textes administratifs de la direction générale",
      "créer les conditions d'accessibilité aux archives",
      "archiver les textes administratifs de la direction générale",
    ],
    "bureau de la documentation": [49,
      "constituer la documentation physique et virtuelle de la direction générale",
      "gérer le fonds documentaire de la direction générale",
    ],
  },
};
