import type { AttributionsParTexte } from "./socle";

/**
 * Les deux directions générales de l'enseignement — arrêtés n° 25565 et 25566.
 *
 * Transcrit du Journal officiel, article par article. Les intitulés sont
 * ceux du texte : c'est par eux que l'entité est retrouvée.
 */
export const ENSEIGNEMENT: AttributionsParTexte = {
  "25565": {
    "secrétariat de direction": [3,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tache qui peut lui être confiée",
    ],
    "bureau du courrier, des relations publiques et de la communication": [5,
      "réceptionner, enregistrer et communiquer le courrier",
      "expédier et diffuser tout document administratif",
      "analyser les correspondances et autres documents administratifs",
      "assurer le suivi du courrier",
      "assurer la diffusion et la circulation des informations en interne et en externe de la direction générale",
      "assurer les relations publiques de la direction générale",
    ],
    "bureau de la saisie et de la reprographie": [6,
      "saisir et reprographier les correspondances et autres documents administratifs",
      "assurer le traitement informatique des données administratives, et, d'une manière générale, exécuter toute autre tache qui peut lui être confiée",
    ],
    "direction de l'enseignement technique du premier cycle": [7,
      "veiller à l'acquisition des connaissances théoriques, des savoirs pratiques nécessaires à l'exercice d'un métier",
      "préparer le mouvement du personnel en fonction des impératifs de la carte scolaire",
      "promouvoir la concertation avec les établissements de formation",
      "participer à l'élaboration, à la mise en œuvre et au suivi des curricula, des méthodes et techniques pédagogiques",
    ],
    "service de l'encadrement pédagogique > service de l'encadrement pédagogique": [9,
      "veiller à l'acquisition des connaissances et renseigner la direction générale sur les besoins en connaissances théoriques et des savoirs pratiques nécessaires à l'exercice d'une profession d'enseignant",
      "participer à l'élaboration des plans de formation du personnel",
      "contribuer à l'élaboration, au suivi des programmes, des méthodes et des techniques pédagogiques",
      "contribuer au perfectionnement et au recyclage du personnel",
    ],
    "service de l'encadrement pédagogique > bureau de l'encadrement et de la formation": [11,
      "garantir la qualification et la compétence pédagogique du personnel enseignant du premier cycle",
      "participer à l'élaboration et à l'exécution des plans de formation du personnel",
      "recenser par filière, le personnel enseignant formé",
      "capitaliser les expériences des autres pays et organismes en matière d'enseignement technique",
      "participer à la définition des supports pédagogiques et administratifs de formation",
      "déterminer les besoins en personnel enseignant du premier cycle, au plan quantitatif et qualitatif",
    ],
    "service de l'encadrement pédagogique > bureau de la recherche et de l'action pédagogique": [12,
      "veiller à l'application des programmes et méthodes pédagogiques dans les établissements de l'enseignement technique du premier cycle",
      "suivre l'activité des groupes de recherche et d'action pédagogique au niveau des départements pédagogiques",
      "élaborer les projets de recherche pédagogique",
      "créer et gérer la banque de données en matière d'actions pédagogiques",
      "promouvoir les initiatives et les innovations en matière de recherche et d'action pédagogiques",
      "promouvoir le partenariat en vue de favoriser l'échange d'expérience",
      "vulgariser les nouvelles méthodes pédagogiques et les nouveaux programmes",
    ],
    "bureau du suivi des établissements techniques privés du premier cycle": [13,
      "assurer la collecte des informations utiles à l'orientation scolaire",
      "veiller à l'application des programmes officiels",
      "participer aux transferts des apprenants entre établissements",
      "collecter les données statistiques des élèves et des établissements",
      "contribuer à la mise à jour de la carte scolaire",
    ],
    "service des études et de la prospective > service des études et de la prospective": [14,
      "participer à l'élaboration ou à la mise à jour des curricula",
      "suivre l'évolution des parcours dans les établissements d'enseignement technique",
      "faire des projections sur des formations ou études en tenant compte des besoins de l'économie nationale",
      "mettre à jour les statistiques scolaires",
      "organiser le mouvement du personnel en fonction des impératifs de la carte scolaire",
      "promouvoir un système de concertation avec les établissements de formation",
    ],
    "service des études et de la prospective > bureau des études et des statistiques": [16,
      "initier à l'attention de la hiérarchie, les projets de curricula , faire le suivi des parcours",
      "dresser les statistiques des élèves, par classe, filière, résultats scolaires, afin de suivre la courbe évolutive des résultats et les interpréter",
      "dresser les statistiques",
      "faire le point annuel des transferts des élèves dans les établissements scolaires",
      "faire des projections sur la rentrée scolaire et des évaluations annuelles",
    ],
    "service des études et de la prospective > bureau de la prospective et de la programmation": [17,
      "analyser les perspectives de développement de l'enseignement technique du premier cycle",
      "étudier l'environnement de formation en vue d'en améliorer l'efficience et l'efficacité",
      "exploiter les données statistiques et faire des projections",
      "participer à l'élaboration des plans de formation du personnel de l'enseignement technique du premier cycle",
    ],
    "direction de l'enseignement technique du deuxième cycle": [18,
      "asseoir et approfondir les acquisitions et les appropriations des connaissances théoriques et des savoirs pratiques et organisationnels reçus depuis les premiers degrés des enseignements général et technique",
      "veiller à l'acquisition des connaissances théoriques et pratiques nécessaires à l'exercice d'un métier",
      "préparer le mouvement du personnel en fonction des impératifs de la carte scolaire",
      "organiser le perfectionnement et le recyclage des agents en activité",
      "préparer les élèves à poursuivre les études supérieures",
      "assurer l'orientation des élèves des collèges d'enseignement technique dans les lycées d'enseignement technique",
      "participer à l'élaboration, à la mise en œuvre et au suivi des curricula, des méthodes et techniques pédagogiques",
    ],
    "service de l'encadrement pédagogique": [20,
      "veiller à l'acquisition des connaissances et renseigner la direction générale sur les besoins en connaissances théoriques et des savoirs pratiques nécessaires à l'exercice d'une profession d'enseignant",
      "participer à l'élaboration des plans de formation du personnel",
      "contribuer à l'élaboration, au suivi des programmes, des méthodes et des techniques pédagogiques",
      "contribuer au perfectionnement et au recyclage du personnel",
    ],
    "bureau de l'encadrement et de la formation": [22,
      "garantir la qualification et la compétence pédagogique du personnel enseignant du deuxième cycle",
      "participer à l'élaboration et à l'exécution des plans de formation des personnels",
      "recenser par filière, le personnel enseignant formé",
      "capitaliser les expériences des autres pays et organismes en matière d'enseignement technique",
      "participer à la définition des supports pédagogiques",
      "déterminer les besoins en personnel enseignant du deuxième cycle, au plan quantitatif et qualitatif",
    ],
    "bureau de la recherche et de l'action pédagogique": [23,
      "veiller à l'application des programmes et méthodes pédagogiques dans les établissements de l'enseignement technique du deuxième cycle",
      "suivre l'activité des groupes de recherche et d'action pédagogique au niveau des départements pédagogiques",
      "élaborer les projets de recherche pédagogique",
      "créer et gérer une banque de données en matière d'actions pédagogiques",
      "être à l'écoute des initiatives et des innovations en matière de recherche et d'action pédagogiques",
      "promouvoir le partenariat en vue de favoriser l'échange d'expériences",
      "vulgariser les nouvelles méthodes et les nouveaux programmes. Scus-section 3 : Du bureau du suivi des établissements techniques privés du deuxième cycle",
    ],
    "bureau du suivi des établissements techniques privés du deuxième cycle": [24,
      "assurer la collecte des informations utiles à l'orientation scolaire",
      "veiller à l'application des programmes officiels",
      "participer et centraliser les transferts et autres mouvements des élèves d'un établissement à un autre pour la maitrise du flux des élèves",
      "collecter les données statistiques des élèves et des établissements",
    ],
    "service des études et de la prospective": [25,
      "proposer les curricula",
      "suivre l'évolution des parcours dans les établissements d'enseignement technique",
      "faire des projections de formations ou études en tenant compte des besoins en présence",
      "tenir les statistiques scolaires",
      "organiser le mouvement des personnels en fonction des impératifs de la carte scolaire",
      "promouvoir un système de concertation avec les établissements de formation",
    ],
    "bureau des études et des statistiques": [27,
      "initier, à l'attention de la hiérarchie, des projets de curricula",
      "faire le suivi des parcours",
      "dresser les statistiques du point de vue des élèves, par classe, filière, résultats scolaires, afin de suivre la courbe évolutive des résultats et les interpréter",
      "dresser les statistiques des ratios professeurs/ élèves et faire des suggestions sur les quotas",
      "assurer et faire le point annuel des transferts des élèves dans les établissements scolaires",
      "faire des projections sur la rentrée scolaire et des évaluations annuelles",
      "dresser les statistiques des personnels enseignants, administratifs, permanents, vacataires, prestataires de service et du matériel des directions et des établissements",
    ],
    "bureau de la prospective et de la programmation": [28,
      "faire des projections de formation ou études en tenant compte des besoins en présence",
      "analyser les perspectives de développement de l'enseignement technique du deuxième cycle",
      "étudier l'environnement de formation en vue d'en améliorer l'efficience et l'efficacité",
      "exploiter les données statistiques et faire des projections",
      "veiller aux engagements pris en adéquation avec les moyens mobilisés et les délais impartis",
      "participer à l'élaboration des plans de formation des personnels de l'enseignement technique du deuxième cycle",
    ],
    "direction de l'administration, des finances et du matériel": [29,
      "élaborer et exécuter le budget",
      "tenir la comptabilité",
      "gérer les ressources humaines",
      "gérer le matériel",
      "gérer les archives et la documentation",
    ],
    "service des finances et du matériel": [31,
      "élaborer le projet du budget de la direction générale ; suivre l'exécution du budget de la direction générale ; assurer la gestion du matériel de la direction générale ; assurer la production des rapports périodiques sur l'exécution du budget de la direction générale",
    ],
    "bureau des finances": [33,
      "collecter les données budgétaires",
      "élaborer l'avant-projet du budget de la direction générale",
      "préparer les engagements des crédits autorisés",
      "suivre l'exécution du budget de la direction générale",
    ],
    "bureau du matériel": [34,
      "gérer le matériel de la direction générale",
      "gérer le stock, assurer le dispatching et l'acheminement du matériel",
      "recevoir et analyser les besoins des différentes structures",
      "mettre à jour le fichier informatisé du matériel de la direction générale",
    ],
    "service des ressources humaines": [35,
      "gérer le personnel",
      "veiller au maintien des bonnes conditions de travail",
      "mettre à jour le fichier informatisé du personnel",
      "suivre la carrière du personnel de la direction générale",
    ],
    "bureau du personnel": [37,
      "gérer les dossiers du personnel de la direction générale",
      "mettre à jour la liste du personnel de la direction générale",
      "suivre les dossiers de la carrière du personnel de la direction générale",
    ],
    "bureau du suivi de la carrière du personnel": [38,
      "participer au suivi des dossiers relatifs à la carrière du personnel de la direction générale",
      "participer aux travaux de la commission d'avancement paritaire",
      "tenir à jour le projet du tableau des avancements du personnel de la direction générale",
      "suivre les mutations et les promotions du personnel de la direction générale",
      "maintenir un contact permanent avec les services de la fonction publique",
    ],
    "service des archives et de la documentation": [39,
      "gérer les archives et la documentation de la direction générale",
      "constituer la mémoire physique et virtuelle de la direction générale",
      "travailler en étroite collaboration avec les services et projets du ministère",
      "recenser et numériser les textes administratifs du ministère",
      "transférer les fichiers numérisés au service des archivages et de la documentation à la direction des systèmes d'information et de la communication",
    ],
    "bureau des archives": [41,
      "collecter et archiver les textes de la direction générale",
      "créer les conditions d'accessibilité aux archives",
    ],
    "bureau de la documentation": [42,
      "constituer la documentation physique et virtuelle de la direction générale",
      "gérer le fonds documentaire de la direction générale",
    ],
  },
  "25566": {
    "secrétariat de direction": [3,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "bureau du courrier, des relations publiques et de la communication": [5,
      "réceptionner, enregistrer et communiquer le courrier",
      "expédier et diffuser tout document administratif",
      "analyser sommairement les correspondances et autres documents administratifs",
      "assurer le suivi du courrier",
      "assurer la diffusion et la circulation des informations en interne et en externe de la direction générale",
      "assurer les relations publiques de la direction générale",
    ],
    "bureau de la saisie et de la reprographie": [6,
      "saisir et reprographier les correspondances et autres documents administratifs",
      "assurer le traitement informatique des données administratives",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "direction des écoles et centres de formation professionnelle": [7,
      "appuyer l'encadrement des activités pédagogiques et administratives dans les établissements publics d'enseignement professionnel",
      "veiller à l'acquisition des connaissances théoriques et des savoirs pratiques nécessaires à l'exercice d'une profession, d'un métier ou d'un emploi",
      "participer à la préparation des concours d'entrée dans les établissements d'enseignement professionnel",
      "veiller à l'application de la réglementation relative à la formation professionnelle",
      "mener toute étude visant à l'amélioration de l'enseignement professionnel",
      "préparer le mouvement du personnel enseignant relevant de son secteur",
      "veiller à la formation professionnelle initiale des personnels enseignants et d'encadrement des établissements",
    ],
    "service de la réglementation": [9,
      "veiller à l'application de la réglementation en vigueur dans les écoles professionnelles et les centres de formation",
      "initier les réformes utiles à la formation pour les écoles professionnelles et les centres de formation",
      "centraliser les textes relatifs à la formation professionnelle",
      "suivre l'évolution de la législation en matière d'enseignement professionnel sur le plan national et sur le plan international",
    ],
    "bureau de la rédaction et de la prospective": [11,
      "initier et proposer les réformes relatives à la formation professionnelle",
      "participer aux travaux de réformes de l'enseignement technique et professionnel",
      "prendre toute initiative en vue d'améliorer les conditions de formation de l'enseignement professionnel",
    ],
    "bureau du contrôle": [12,
      "contrôler l'effectivité de la règlementation",
      "suivre l'évolution de la législation en matière d'enseignement professionnel sur les plans national et international",
      "dresser des rapports sur les insuffisances ou l'évolution de la réglementation",
    ],
    "service pédagogique": [13,
      "suivre les activités pédagogiques des établissements de l'enseignement professionnel et des écoles spécialisées",
      "examiner les problèmes pédagogiques que pose le fonctionnement des établissements d'enseignement professionnel",
      "appuyer les activités d'encadrement pédagogique et administratif dans les établissements d'enseignement professionnel",
      "veiller à la formation professionnelle initiale des personnels enseignant et d'encadrement des établissements d'enseignement professionnel",
      "définir les objectifs de formation",
      "organiser les activités d'encadrement et d'évaluation pédagogiques avec le secteur productif et les autres ministères",
      "contribuer à l'amélioration de la qualité des enseignements dispensés",
      "participer à l'organisation des concours d'entrée et des examens de sortie des établissements d'enseignement professionnel",
    ],
    "bureau du suivi des activités pédagogiques": [15,
      "maintenir le contrôle permanent des activités pédagogiques dans les établissements d'enseignement professionnel",
      "contribuer à l'amélioration de la qualité des enseignements dispensés dans les établissements d'enseignement professionnel",
      "travailler en collaboration avec l'inspection générale",
      "dresser les rapports du suivi des activités pédagogiques",
    ],
    "bureau du suivi et de l'évaluation des programmes": [16,
      "travailler en étroite collaboration avec les services de l'inspection générale pour le suivi et l'évaluation des programmes",
      "suivre et évaluer les activités des stages dans les établissements d'enseignement professionnel",
      "veiller à la bonne organisation des évaluations pédagogiques périodiques dans les établissements d'enseignement professionnel",
      "collecter et exploiter les informations et documents relatifs à l'expérience des établissements des autres États",
    ],
    "direction de la formation des formateurs et de la formation permanente": [17,
      "veiller à la formation continue des formateurs du sous-secteur",
      "tenir à jour le fichier et les statistiques des stagiaires du sous-secteur",
      "promouvoir une politique de conservation, de recyclage et de perfectionnement en adéquation avec les besoins de développement économique, social et culturel du pays",
      "participer à la préparation des concours de formation professionnelle organisés par l'État",
      "suivre la scolarité des agents du ministère admis en stage, tant à l'intérieur qu'à l'extérieur du pays",
      "veiller au recyclage des agents du ministère",
      "tenir régulièrement informés les services employeurs des offres de formation et de la situation académique de leurs agents en stage",
      "assurer le secrétariat technique de la souscommission des stages de la commission nationale des ressources humaines",
    ],
    "service de la formation des formateurs": [19,
      "travailler en étroite collaboration avec les services de l'inspection générale pour la mise en oeuvre des programmes de formation des formateurs",
      "organiser la formation des formateurs",
      "initier les programmes adaptés de la formation des formateurs",
      "suivre et contrôler la formation des formateurs",
    ],
    "bureau des études et de la programmation": [21,
      "identifier les domaines de formation avec les autres services impliqués",
      "établir et suivre les programmes de formation",
      "identifier à l'attention de la hiérarchie, les enseignants concernés par la formation",
    ],
    "bureau du suivi et du contrôle": [22,
      "suivre et contrôler la formation des formateurs",
      "organiser le suivi des formateurs en formation",
      "collaborer avec l'inspection générale dans le cadre de la formation",
      "établir les rapports mensuels",
    ],
    "service des stages et de la formation permanente": [23,
      "gérer les stages des apprenants des écoles professionnelles et centres de formation professionnelle",
      "élaborer les programmes de stages en collaboration avec les établissements d'enseignements professionnels",
      "suivre la scolarité et la performance des apprenants",
      "assurer la formation permanente et continue des agents du ministère",
      "suivre la performance des agents formés",
      "promouvoir les stages de formation et de perfectionnement",
      "entretenir des contacts avec les partenaires en synergie avec la direction de la coopération et du partenariat",
      "mettre à jour le fichier du personnel formé et les statistiques des stagiaires",
      "préparer, de concert avec les services impliqués, les sessions de la sous-commission des stages de la commission nationale des ressources humaines",
    ],
    "bureau des stages": [25,
      "initier les programmes de stages en collaboration avec les établissements de formation professionnelle",
      "mettre en œuvre les programmes de stages",
      "recevoir et traiter initialement les dossiers de stages",
      "suivre la scolarité et le déroulement de stages",
      "suivre la performance des apprenants en stage",
      "tenir les statistiques des stagiaires à l'intérieur et à l'extérieur du pays",
      "préparer la tenue des sessions de la souscommission des stages de la commission nationale des ressources humaines",
      "mettre à jour le fichier du personnel formé et les statistiques des stagiaires",
    ],
    "bureau de la formation permanente": [26,
      "initier la planification des formations continue et permanente du personnel",
      "mettre en œuvre les programmes de formation permanente et continue des agents",
      "œuvrer pour la promotion de la formation permanente",
      "mettre à jour le fichier informatisé du personnel formé",
    ],
    "direction de l'administration, des finances et du matériel": [27,
      "élaborer et exécuter le budget",
      "tenir la comptabilité",
      "gérer les ressources humaines",
      "gérer le matériel",
      "gérer les archives et la documentation",
    ],
    "service des finances et du matériel": [29,
      "élaborer le projet de budget de la direction générale",
      "suivre l'exécution du budget de la direction générale",
      "assurer la gestion des biens meubles et immeubles de la direction générale",
      "assurer la production des rapports périodiques sur l'exécution du budget de la direction générale",
    ],
    "bureau des finances": [31,
      "collecter les données budgétaires",
      "élaborer l'avant-projet de budget de la direction générale",
      "préparer les engagements des crédits autorisés",
      "suivre l'exécution du budget de la direction générale",
    ],
    "bureau du matériel": [32,
      "gérer le matériel de la direction générale",
      "gérer le stock, assurer le dispatching et l'acheminement du matériel",
      "recevoir et analyser les besoins des différentes structures",
      "mettre à jour le fichier informatisé du matériel de la direction générale",
    ],
    "service des ressources humaines": [33,
      "gérer le personnel",
      "veiller au maintien des bonnes conditions de travail",
      "mettre à jour le fichier informatisé du personnel",
      "participer au suivi de la carrière du personnel de la direction générale",
    ],
    "bureau du personnel": [35,
      "gérer les dossiers du personnel de la direction générale",
      "mettre à jour la liste du personnel de la direction générale",
      "suivre les dossiers relatifs à la carrière du personnel de la direction générale",
    ],
    "bureau du suivi de la carrière du personnel": [36,
      "participer au suivi des dossiers relatifs à la carrière du personnel de la direction générale",
      "participer aux travaux de la commission d'avancement paritaire",
      "tenir à jour le projet de tableau des avancements du personnel de la direction générale",
      "suivre les mutations et les promotions du personnel de la direction générale",
      "maintenir un contact permanent avec les services de la fonction publique",
    ],
    "service des archives et de la documentation": [37,
      "gérer les archives et la documentation de la direction générale",
      "constituer la mémoire physique et virtuelle de la direction générale",
      "travailler en étroite collaboration avec les services et les projets du ministère",
      "recenser et numériser les textes administratifs du ministère",
      "transférer les fichiers numérisés au service des archives et de la documentation à la direction des systèmes d'information et de la communication",
    ],
    "bureau des archives": [39,
      "collecter les textes administratifs de la direction générale",
      "créer les conditions d'accessibilité aux archives",
      "archiver les textes administratifs de la direction générale",
    ],
    "bureau de la documentation": [40,
      "constituer la documentation physique et virtuelle de la direction générale",
      "gérer le fonds documentaire de la direction générale",
    ],
  },
};
