import type { AttributionsParTexte } from "./socle";

/**
 * La direction générale de l'équipement et du patrimoine — arrêté n° 25568.
 *
 * Transcrit du Journal officiel, article par article. Les intitulés sont
 * ceux du texte : c'est par eux que l'entité est retrouvée.
 */
export const EQUIPEMENT: AttributionsParTexte = {
  "25568": {
    "secrétariat de direction": [3,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "bureau du courrier, des relations publiques et de la communication": [5,
      "réceptionner, enregistrer et communiquer le courrier",
      "expédier et diffuser tout document administratif",
      "analyser sommairement les correspondances et autres documents administratifs",
      "assurer le suivi du courrier",
      "assurer la diffusion et la circulation des informations en interne et en externe",
      "assurer les relations publiques de la direction générale",
    ],
    "bureau de la saisie et de la reprographie": [6,
      "saisir et reprographier les correspondances et autres documents administratifs",
      "assurer le traitement informatique des données administratives",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "direction de l'équipement et du patrimoine": [7,
      "appliquer la politique foncière en vigueur concernant le ministère",
      "assurer l'équipement du ministère",
      "gérer le patrimoine du ministère",
      "tenir le fichier informatisé du patrimoine mobilier et immobilier du ministère",
      "veiller à la protection des biens mobiliers et immobiliers",
      "veiller à l'immatriculation des biens immobiliers du ministère",
    ],
    "service de l'équipement": [9,
      "dresser l'inventaire des équipements",
      "établir les besoins du ministère",
      "assurer les acquisitions et le dispatching des équipements du ministère",
      "veiller à la bonne utilisation de l'équipement",
      "mettre à jour le fichier physique et informatisé de l'équipement",
    ],
    "bureau des acquisitions": [11,
      "assurer les acquisitions du ministère en matière d'équipement",
      "assurer le dispatching et l'acheminement du matériel",
      "veiller à l'assurance des équipements du ministère",
      "veiller à la bonne utilisation de l'équipement acquis",
    ],
    "service de l'équipement > bureau du fichier": [12,
      "faire l'inventaire de l'équipement acquis",
      "établir les besoins en équipement du ministère",
      "mettre à jour le fichier informatisé de l'équipement",
    ],
    "service du patrimoine": [13,
      "faire l'inventaire du patrimoine du ministère",
      "gérer le patrimoine du ministère",
      "sécuriser le patrimoine mobilier et immobilier du ministère",
      "contribuer à l'accroissement du patrimoine du ministère",
      "veiller à l'immatriculation et à la bonne utilisation du patrimoine du ministère",
      "mettre à jour le fichier physique et informatisé du patrimoine du ministère",
    ],
    "bureau de la gestion du patrimoine": [15,
      "gérer le patrimoine du ministère",
      "sécuriser le patrimoine mobilier et immobilier du ministère",
      "assurer l'immatriculation du patrimoine immobilier du ministère",
      "contribuer à l'accroissement du patrimoine du ministère",
      "veiller à la bonne utilisation du patrimoine",
    ],
    "service du patrimoine > bureau du fichier": [16,
      "faire l'inventaire complet du patrimoine",
      "tenir la banque des titres de propriété",
      "mettre à jour le fichier informatisé des biens meubles et immeubles du ministère",
    ],
    "service du contentieux": [17,
      "gérer le contentieux en matière d'équipement et de patrimoine",
      "gérer le contentieux relatif aux appels d'offre",
      "contrôler la régularité des acquisitions",
      "contrôler les fichiers de l'équipement et du patrimoine",
    ],
    "bureau des réclamations": [19,
      "recevoir toutes réclamations relatives au patrimoine et à l'équipement",
      "analyser toutes réclamations et faire suivre",
      "prévenir et anticiper le règlement du contentieux",
    ],
    "bureau du contrôle": [20,
      "assurer le contrôle des acquisitions d'équipements et du patrimoine du ministère",
      "veiller à la régularité des fichiers de l'équipement et du patrimoine du ministère",
      "procéder régulièrement aux contrôles de l'équipement et du patrimoine du ministère",
    ],
    "direction de l'administration, des finances et du matériel": [21,
      "élaborer et exécuter le budget",
      "tenir la comptabilité",
      "gérer les ressources humaines",
      "gérer le matériel",
      "gérer les archives et la documentation",
    ],
    "service des finances et du matériel": [23,
      "élaborer le projet de budget de la direction générale",
      "suivre l'exécution du budget de la direction générale",
      "assurer la gestion des biens meubles et immeubles de la direction générale",
      "assurer la production des rapports périodiques sur l'exécution du budget de la direction générale",
    ],
    "bureau des finances": [25,
      "collecter les données budgétaires",
      "élaborer l'avant-projet de budget de la direction générale",
      "préparer les engagements des crédits autorisés",
      "suivre l'exécution du budget de la direction générale",
    ],
    "bureau du matériel": [26,
      "gérer le matériel de la direction générale",
      "gérer le stock, assurer le dispatching et l'acheminement du matériel",
      "recevoir et analyser les besoins des différentes structures",
      "mettre à jour le fichier informatisé du matériel de la direction générale",
    ],
    "service des ressources humaines": [27,
      "gérer le personnel",
      "veiller au maintien des bonnes conditions de travail",
      "mettre à jour le fichier informatisé du personnel",
      "participer au suivi de la carrière du personnel relevant de la direction générale",
    ],
    "bureau du personnel": [29,
      "gérer les dossiers du personnel de la direction générale",
      "mettre à jour la liste du personnel de la direction générale",
      "suivre les dossiers relatifs à la carrière du personnel de la direction générale",
    ],
    "bureau du suivi de la carrière du personnel": [30,
      "participer au suivi des dossiers relatifs à la carrière du personnel de la direction générale",
      "participer aux travaux de la commission d'avancement paritaire",
      "tenir à jour le projet de tableau des avancements du personnel de la direction générale",
      "suivre les mutations et les promotions du personnel de la direction générale",
      "maintenir un contact permanent avec les services de la fonction publique",
    ],
    "service des archives et de la documentation": [31,
      "gérer les archives et la documentation de la direction générale",
      "constituer la mémoire physique et virtuelle de la direction générale",
      "travailler en étroite collaboration avec les services et projets du ministère",
      "recenser et numériser les textes administratifs du ministère",
      "transférer les fichiers numérisés au service des archivages et de la documentation à la direction des systèmes d'information et de la communication",
    ],
    "bureau des archives": [33,
      "collecter les textes administratifs de la direction générale",
      "créer les conditions d'accessibilité aux archives",
      "archiver les textes administratifs de la direction générale",
    ],
    "bureau de la documentation": [34,
      "constituer la documentation physique et virtuelle de la direction générale",
      "gérer le fonds documentaire de la direction générale",
    ],
  },
};
