import type { AttributionsParTexte } from "./socle";

/**
 * L'inspection générale — arrêté n° 25569.
 *
 * Transcrit du Journal officiel, article par article. Les intitulés sont
 * ceux du texte : c'est par eux que l'entité est retrouvée.
 */
export const INSPECTION: AttributionsParTexte = {
  "25569": {
    "secrétariat de direction": [3,
      "réceptionner et expédier le courrier",
      "analyser sommairement les correspondances et autres documents administratifs",
      "saisir et reprographier les correspondances et autres documents administratifs",
      "et, d'une manière générale, exécuter toute autre tâche qui peut lui être confiée",
    ],
    "bureau du courrier, des relations publiques et de la communication": [5,
      "réceptionner, enregistrer et communiquer le courrier",
      "expédier et diffuser tout document administratif",
      "analyser les correspondances et autres documents administratifs",
      "assurer le suivi du courrier",
      "assurer la diffusion et la circulation des informations en interne et en externe de l'inspection générale",
      "assurer les relations publiques de l'inspection générale",
    ],
    "bureau de la saisie et de la reprographie": [6,
      "saisir et reprographier les correspondances et autres documents administratifs",
      "assurer le traitement informatique des données administratives",
      "exécuter toute autre tâche qui peut lui être confiée",
    ],
    "direction des affaires administratives et financières": [7,
      "gérer les ressources humaines de l'inspection générale",
      "gérer les ressources financières et le patrimoine de l'inspection générale",
      "gérer les archives et la documentation de l'inspection générale",
    ],
    "service des ressources humaines": [9,
      "assurer le contrôle au plan administratif et du personnel de l'inspection générale",
      "participer à l'élaboration et à l'exécution des plans de formation du personnel de l'inspection générale",
      "veiller au perfectionnement et au recyclage du personnel de l'inspection générale",
      "tenir le fichier nominatif et les dossiers du personnel de l'inspection générale",
      "gérer les situations administratives du personnel de l'inspection générale",
    ],
    "bureau des affaires administratives": [11,
      "assurer le contrôle au plan administratif et du personnel de l'inspection générale",
      "gérer les situations administratives du personnel de l'inspection générale",
      "tenir le fichier et les dossiers du personnel de l'inspection générale",
    ],
    "bureau de la formation": [12,
      "participer à l'élaboration et à l'exécution des plans de formation du personnel",
      "mettre en œuvre les formations ou recyclages des inspecteurs",
      "veiller au perfectionnement et au recyclage des agents de l'inspection générale en cours d'activité",
      "tenir les statistiques des formations ou recyclages des agents de l'inspection générale",
    ],
    "service des finances et du matériel": [13,
      "élaborer le projet du budget de l'inspection générale",
      "suivre l'exécution du budget de l'inspection générale",
      "assurer la gestion du matériel de l'inspection générale",
      "assurer la production de rapports périodiques sur l'exécution du budget de l'inspection générale",
    ],
    "bureau des finances": [15,
      "collecter les données budgétaires",
      "élaborer l'avant-projet du budget de l'inspection générale",
      "préparer les engagements des crédits autorisés",
      "suivre l'exécution du budget de l'inspection générale",
    ],
    "bureau du matériel": [16,
      "gérer le matériel de l'inspection générale",
      "gérer le stock, assurer le dispatching et l'acheminement du matériel des structures de l'inspection générale",
      "recevoir et analyser les besoins en matériel des structures de l'inspection générale",
      "mettre à jour le fichier informatisé du matériel de l'inspection générale",
    ],
    "service des archives et de la documentation": [17,
      "gérer les archives et la documentation de l'inspection générale",
      "constituer la mémoire physique et virtuelle de l'inspection générale",
      "recenser et numériser les textes de l'inspection générale",
      "transférer les fichiers numérisés au service des archivages et de la documentation à la direction des systèmes d'information et de la communication",
    ],
    "bureau des archives": [19,
      "collecter les textes de l'inspection générale",
      "créer des conditions d'accessibilité aux archives",
      "archiver les textes de l'inspection générale",
    ],
    "bureau de la documentation": [20,
      "constituer la documentation physique et virtuelle de l'inspection générale",
      "gérer le fonds documentaire de l'inspection générale",
    ],
    "inspection pédagogique": [21,
      "effectuer des missions d'inspection, de contrôle et d'évaluation",
      "participer à la conception et à la rédaction des programmes d'études",
      "participer à la conception des supports didactiques",
      "organiser le contrôle de l'encadrement pédagogique",
      "analyser et évaluer les programmes, les méthodes et les techniques pédagogiques",
      "analyser, évaluer, contrôler et suivre les rapports d'inspection pédagogique en provenance des établissements scolaires, des inspections et directions départementales",
      "participer à l'élaboration et à l'exécution des plans de formation des personnels d'encadrement pédagogique",
      "veiller au perfectionnement et au recyclage des agents en cours d'activité",
      "promouvoir les politiques et innovations pédagogiques",
      "analyser et évaluer les résultats scolaires",
      "suivre l'organisation et le déroulement des examens d'État et concours techniques et professionnels",
    ],
    "division de la recherche, de l'innovation et de la pédagogie": [23,
      "promouvoir, mettre en œuvre et coordonner les initiatives et la recherche visant l'innovation pédagogique et technologique",
      "œuvrer pour le développement de la qualité scolaire et des pratiques pédagogiques",
    ],
    "section de l'innovation pédagogique et technologique": [25,
      "accompagner les personnels enseignants dans l'évolution de leurs pratiques pédagogiques",
      "assurer des formations courtes et ciblées en fonction des demandes reçues ou recueillies lors d'enquêtes",
      "assurer la diffusion d'informations concernant la pratique pédagogique",
      "mettre en place des démarches de sensibilisation à l'usage du numérique",
      "faciliter la mise en exécution des projets relatifs au numérique",
    ],
    "section du développement du matériel didactique": [26,
      "produire des ressources informatisées et des documents imprimés conçus à l'intention des enseignants et des apprenants",
      "s'assurer que le matériel pédagogique de qualité est mis à la disposition des apprenants",
      "contribuer à l'élaboration du matériel pédagogique",
      "accompagner les enseignants dans la réalisation des projets de développement du matériel didactique",
      "fournir au ministère, aux établissements scolaires, aux centres de formation, aux différentes parties prenantes, des informations, des données actualisées et exploitables relatives au matériel didactique",
      "participer à l'élaboration, à la mise en œuvre et à l'analyse des enquêtes en matière d'évaluation du système éducatif du sous-secteur de l'enseignement technique et professionnel",
    ],
    "division de l'évaluation des programmes et des méthodes": [27,
      "analyser et évaluer l'exécution des programmes de formation, des méthodes et techniques d'enseignement",
      "assurer le suivi et le contrôle de l'exécution des programmes de formation",
      "promouvoir les réformes et les innovations dans les méthodes d'enseignement et d'évaluation ainsi que les moyens pédagogiques correspondant aux contenus des programmes",
      "participer aux réformes des programmes d'études et des méthodes pédagogiques",
      "participer à l'élaboration et à l'actualisation des programmes d'études techniques et professionnelles",
      "participer à l'organisation et au déroulement des concours et examens d'État",
    ],
    "section de l'élaboration des curricula": [29,
      "créer une base de données en vue de l'élaboration ou de l'actualisation des programmes d'études",
      "participer à la réalisation des études sur les portraits des secteurs de formation",
      "participer à l'élaboration des nouveaux programmes d'études actualiser les programmes d'études existants",
      "mettre à jour le fichier national des entreprises et le répertoire des diplômes et des métiers",
      "suivre l'exécution des programmes d'études, l'application des méthodes et techniques d'enseignement",
      "assurer la veille sectorielle",
    ],
    "section de l'évaluation des programmes d'études et des méthodes pédagogiques": [30,
      "exploiter les rapports pédagogiques et autres documents en provenance des inspections départementales, des établissements scolaires et des autres entités administratives",
      "analyser les besoins indispensables à l'évaluation des programmes d'études et des résultats des actions de formation sur l'évolution du marché du travail",
      "évaluer les programmes d'études et les méthodes pédagogiques",
      "analyser et évaluer les résultats scolaires et les résultats des concours et examens d'État",
    ],
    "inspection des finances, de l'équipement et du patrimoine": [31,
      "concevoir, produire et vulgariser les supports de contrôle de gestion en matière financière, d'équipement et de patrimoine du ministère",
      "contrôler la gestion des subventions, des crédits alloués, des bourses scolaires et de toute contribution accordée aux structures du ministère",
      "contrôler la gestion du patrimoine du ministère",
      "proposer des mesures susceptibles d'améliorer la gestion des finances et du patrimoine du ministère",
    ],
    "division des finances": [33,
      "contrôler la gestion des subventions, des crédits alloués, des bourses, aides scolaires et de toute autre contribution accordées aux différentes structures du ministère",
      "contrôler toutes les procédures requises relatives à la protection des actifs et à la production d'informations financières",
      "contrôler l'exécution des budgets de fonctionnement et d'investissement du ministère",
      "proposer des mesures susceptibles d'améliorer la gestion des finances du ministère",
      "contrôler les états financiers, la gestion de la trésorerie, la perception des comptes et l'acquisition des biens et services",
    ],
    "section du contrôle financier": [35,
      "contrôler la régularité des dépenses des entités administratives placées sous la tutelle ou l'autorité du ministère en charge de l'enseignement technique et professionnel",
      "faire part à la hiérarchie des conditions dans lesquelles s'effectue la gestion financière des entités administratives placées sous la tutelle ou l'autorité du ministre chargé de l'enseignement technique et professionnel et suggérer toute mesure corrective pouvant améliorer cette gestion",
      "assurer les missions de vérification",
      "participer aux missions d'enquête",
    ],
    "section des études, de la documentation et de l'informatique": [36,
      "mener des études relatives à la gestion financière des entités administratives du ministère",
      "réunir et traiter toutes les informations économiques et financières pour une meilleure gestion des dossiers",
      "concevoir, produire et vulgariser les supports de contrôle de gestion en matière financière du ministère",
    ],
    "division de l'équipement et du patrimoine": [37,
      "produire et vulgariser les supports de contrôle de gestion en matière d'équipement et de patrimoine du ministère",
      "contrôler la gestion du patrimoine mobilier et immobilier du ministère",
      "assurer le contrôle de l'approvisionnement en équipement des structures relevant du ministère",
      "mettre à jour le fichier du patrimoine mobilier et immobilier du ministère",
    ],
    "section du contrôle de l'équipement": [39,
      "produire et vulgariser les supports de contrôle de gestion en matière d'équipement du ministère",
      "assurer le contrôle de l'approvisionnement en équipement et en matériel",
      "mettre à jour le fichier informatisé des équipements du ministère",
    ],
    "section du contrôle du patrimoine": [40,
      "contrôler le patrimoine du ministère",
      "contrôler les procédures d'acquisition du patrimoine",
      "mettre à jour le fichier informatisé du patrimoine mobilier et immobilier du ministère",
    ],
    "inspection des affaires administratives et des ressources humaines": [41,
      "assurer le contrôle sur le plan administratif, des personnels et des services à tous les niveaux de l'enseignement technique et professionnel",
      "analyser et évaluer les rapports administratifs en provenance des établissements scolaires, des inspections et des directions interdépartementales ainsi que des directions centrales",
      "participer à l'élaboration et à l'exécution des plans de formation des personnels administratifs",
      "veiller au perfectionnement et au recyclage des agents actifs",
      "assurer l'expertise auprès de tous les organes du ministère",
    ],
    "division du contrôle administratif": [43,
      "tenir à jour les statistiques du personnel administratif et enseignant du sous-secteur",
      "assurer le contrôle de la gestion administrative des administrations centrales, départementales et scolaires",
      "veiller à l'utilisation rationnelle du personnel administratif",
      "veiller au respect des normes administratives et de la réglementation en vigueur",
      "veiller à la bonne tenue des documents administratifs",
      "contrôler l'efficacité et l'efficience des actions de formation du personnel administratif",
      "exploiter et analyser les rapports et tout autre document administratif en provenance des structures scolaires, départementales et centrales",
    ],
    "section du contrôle administratif et de la réglementation": [45,
      "contrôler la gestion administrative des administrations centrales, départementales et scolaires",
      "exploiter et analyser les différents rapports et tout autre document administratif en provenance des structures scolaires, départementales et centrales",
      "veiller au respect de la réglementation en vigueur en matière administrative",
      "veiller à la bonne tenue des documents administratifs",
      "suivre la tenue des archives et de la documentation dans toutes les entités administratives et scolaires",
    ],
    "section de la prévision et des statistiques": [46,
      "veiller à la gestion rationnelle du personnel enseignant et administratif",
      "participer à la veille du renforcement des compétences du personnel enseignant et administratif",
      "mettre à jour les statistiques",
      "suivre l'élaboration de la carte scolaire",
    ],
    "division des ressources humaines": [47,
      "contrôler l'élaboration et la mise en œuvre de la politique des ressources humaines du soussecteur",
      "suivre la mise en œuvre des plans d'actions, et le pilotage de leur exécution",
      "contrôler la formation et le développement des compétences du personnel administratif et enseignant",
      "superviser la gestion administrative du personnel",
    ],
    "section du contrôle de la gestion des ressources humaines": [49,
      "contrôler l'élaboration et la mise en œuvre de la politique des ressources humaines du soussecteur",
      "contrôler les critères, les modalités et les conditions de la mise en œuvre du mouvement du personnel",
      "procéder à des enquêtes de moralité des personnels du ministère",
    ],
    "section du contrôle du suivi de l'évolution de la carrière administrative": [50,
      "contrôler le suivi de l'évolution de la carrière administrative du personnel du ministère",
      "analyser les problèmes relatifs à la gestion de la carrière administrative du personnel du ministère",
      "contrôler la gestion de la banque de données relative à l'évolution de la carrière administrative du personnel du ministère",
    ],
    "inspection du management et de l'assurance qualité": [51,
      "participer à la conception des méthodes et des outils du management de la formation dans toutes ses dimensions, qui incluent la stratégie, l'ingénierie de formation, la règlementation, le financement des actions de formation, les pédagogies différentielles",
      "évaluer les besoins en formation du personnel enseignant et administratif",
      "contribuer à la définition globale de la politique qualité du sous-secteur de l'enseignement technique et professionnel",
      "développer des dispositifs de l'ingénierie de formation",
      "concevoir les procédures garantissant la qualité de l'enseignement technique et professionnel",
      "suivre le contrôle de la qualité des personnels enseignants et des outils didactiques",
      "concevoir des solutions pour optimiser la qualité du système éducatif",
      "contrôler la qualité des prestations des personnels à tous les niveaux",
      "participer à la formation du personnel aux méthodes qualité",
    ],
    "division du management": [53,
      "participer à la conception des méthodes et des outils du management de la formation dans toutes ses dimensions",
      "évaluer les besoins en formation du personnel enseignant et administratif",
      "développer des dispositifs d'ingénierie de formation",
    ],
    "section des méthodes et outils du management": [55,
      "concevoir les méthodes et les outils du management de la formation",
      "évaluer les besoins en formation du personnel enseignant et administratif",
    ],
    "section de l'ingénierie de la formation": [56,
      "évaluer les besoins en formation du personnel enseignant et administratif",
      "accompagner les ressources humaines du ministère dans l'élaboration et la réalisation des plans de formation",
      "promouvoir le développement des compétences du personnel du ministère",
    ],
    "division de l'assurance qualité": [57,
      "participer à la définition globale de la politique qualité du sous-secteur de l'enseignement technique et professionnel",
      "identifier et actualiser les critères de performance des enseignants et produire les rapports y relatifs",
      "concevoir les procédures garantissant la qualité de l'enseignement technique et professionnel",
      "suivre le contrôle de la qualité du personnel enseignant et des outils didactiques",
      "produire les données et les statistiques détaillées relatives à l'enseignement technique et professionnel",
      "assurer la qualité et la sécurité des données et statistiques",
      "participer à la formation du personnel aux méthodes qualité",
    ],
    "section du contrôle qualité": [59,
      "participer à la conception des procédures garantissant la qualité de la formation technique et professionnelle",
      "contrôler la qualité du personnel du ministère et les outils didactiques",
    ],
    "section du contrôle de la formation": [60,
      "contrôler et évaluer les besoins en formation du personnel du sous-secteur de l'enseignement technique et professionnel aux méthodes de l'assurance qualité",
      "participer à la conception des procédures garantissant la qualité de l'enseignement technique et professionnel",
      "suivre la formation du personnel du soussecteur de l'enseignement technique et professionnel aux méthodes de l'assurance qualité",
    ],
  },
};
